[workspace]
resolver = "2"
members = [
    "crates/haki_ast",
    "crates/haki_lexer",
    "crates/haki_parser",
    "crates/haki_typeck",
    "crates/haki_mono",
    "crates/haki_codegen",
    "crates/haki_wasm",
    "crates/haki_stdlib",
    "crates/haki_cemit",
    "hakic",
]

[workspace.package]
version     = "0.1.0"
edition     = "2021"
authors     = ["Haki Contributors"]
license     = "MIT"

[workspace.dependencies]
haki_ast    = { path = "crates/haki_ast" }
haki_lexer  = { path = "crates/haki_lexer" }
haki_parser = { path = "crates/haki_parser" }
haki_typeck = { path = "crates/haki_typeck" }
haki_mono   = { path = "crates/haki_mono" }
haki_codegen= { path = "crates/haki_codegen" }
haki_wasm   = { path = "crates/haki_wasm" }
haki_stdlib = { path = "crates/haki_stdlib" }
haki_cemit  = { path = "crates/haki_cemit" }
thiserror   = "1"
