/* Generated by hakic --emit-c (Haki bootstrap emitter) */
/* Compile: gcc -std=gnu11 -O2 -lpthread -lm -o out this.c */

/* haki_runtime.c — Haki v0.1 runtime
   Compile: clang -c haki_runtime.c -o haki_runtime.o               */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdatomic.h>
#include <ctype.h>
#include <errno.h>

/* ── ARC ─────────────────────────────────────────────────────────── */

typedef struct {
    _Atomic int64_t refcount;
    void (*destructor)(void*);
} HakiObjHeader;

void haki_retain(void* obj) {
    if (!obj) return;
    atomic_fetch_add_explicit(
        &((HakiObjHeader*)obj)->refcount, 1, memory_order_relaxed);
}

void haki_release(void* obj) {
    if (!obj) return;
    HakiObjHeader* h = (HakiObjHeader*)obj;
    int64_t prev = atomic_fetch_sub_explicit(
        &h->refcount, 1, memory_order_acq_rel);
    if (prev == 1) {
        if (h->destructor) h->destructor(obj);
        free(obj);
    }
}

void* haki_alloc(int64_t size) {
    void* p = calloc(1, (size_t)size);
    if (!p) { fprintf(stderr, "haki: out of memory\n"); abort(); }
    atomic_store_explicit(
        &((HakiObjHeader*)p)->refcount, 1, memory_order_relaxed);
    return p;
}

void* haki_weak_load(void** slot) {
    void* obj = *slot;
    if (!obj) return NULL;
    int64_t rc = atomic_load_explicit(
        &((HakiObjHeader*)obj)->refcount, memory_order_acquire);
    return (rc > 0) ? obj : NULL;
}

/* ── Print ───────────────────────────────────────────────────────── */

void haki_print(const char* msg) {
    if (!msg) msg = "(null)";
    puts(msg);
}

void haki_print_int(int64_t n) {
    printf("%lld\n", (long long)n);
}

void haki_print_float(double f) {
    printf("%g\n", f);
}

void haki_print_bool(int8_t b) {
    puts(b ? "true" : "false");
}

/* ── String utilities ────────────────────────────────────────────── */

void* haki_string_concat(const char* a, const char* b) {
    if (!a) a = "";
    if (!b) b = "";
    size_t la = strlen(a), lb = strlen(b);
    char* r = (char*)malloc(la + lb + 1);
    if (!r) abort();
    memcpy(r, a, la);
    memcpy(r + la, b, lb + 1);
    return r;
}

int64_t haki_string_length(const char* s) {
    return s ? (int64_t)strlen(s) : 0;
}

/* Returns a heap-allocated string — caller owns it. */
void* haki_int_to_string(int64_t n) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%lld", (long long)n);
    return strdup(buf);
}

void* haki_float_to_string(double f) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%g", f);
    return strdup(buf);
}

void* haki_bool_to_string(int8_t b) {
    return strdup(b ? "true" : "false");
}

/* Bootstrap alias: Haki source calls bool_to_string() directly */
void* bool_to_string(int64_t b) {
    return strdup(b ? "true" : "false");
}

/* ── Panic ───────────────────────────────────────────────────────── */

void haki_panic(const char* msg) {
    fflush(stdout);  /* flush buffered output before aborting */
    fprintf(stderr, "\nhaki panic: %s\n", msg ? msg : "(no message)");
    abort();
}

/* ── Array<T> ───────────────────────────────────────────────────── */

typedef struct {
    int64_t length;
    int64_t capacity;
    void*   data;
    int64_t elem_size;
} HakiArray;

HakiArray* haki_array_new(int64_t elem_size) {
    HakiArray* a = (HakiArray*)malloc(sizeof(HakiArray));
    if (!a) abort();
    a->length    = 0;
    a->capacity  = 8;
    a->elem_size = elem_size;
    a->data      = malloc((size_t)(8 * elem_size));
    if (!a->data) abort();
    return a;
}

HakiArray* haki_array_from(void* src, int64_t count, int64_t elem_size) {
    HakiArray* a = haki_array_new(elem_size);
    a->length   = count;
    a->capacity = count > 8 ? count : 8;
    free(a->data);
    a->data = malloc((size_t)(a->capacity * elem_size));
    if (!a->data) abort();
    if (src && count > 0) memcpy(a->data, src, (size_t)(count * elem_size));
    return a;
}

void haki_array_append(HakiArray* a, void* item) {
    if (!a) return;
    if (a->length == a->capacity) {
        a->capacity *= 2;
        a->data = realloc(a->data, (size_t)(a->capacity * a->elem_size));
        if (!a->data) abort();
    }
    memcpy((char*)a->data + a->length * a->elem_size, item, (size_t)a->elem_size);
    a->length++;
}

void* haki_array_get(HakiArray* a, int64_t idx) {
    if (!a || idx < 0 || idx >= a->length) {
        fprintf(stderr, "haki panic: array index %lld out of bounds (length %lld)\n",
            (long long)idx, a ? (long long)a->length : 0LL);
        abort();
    }
    return (char*)a->data + idx * a->elem_size;
}

int64_t haki_array_length(HakiArray* a) {
    return a ? a->length : 0;
}

void haki_array_free(HakiArray* a) {
    if (a) { free(a->data); free(a); }
}

/* removeLast: pop the last element; returns pointer to it (caller must read
   before next append which may realloc). Returns NULL if empty.             */
void* haki_array_remove_last(HakiArray* a) {
    if (!a || a->length == 0) return NULL;
    a->length--;
    return (char*)a->data + a->length * a->elem_size;
}

/* removeAt: remove element at index, shift left, return heap copy of element. */
void* haki_array_remove_at(HakiArray* a, int64_t idx) {
    if (!a || idx < 0 || idx >= a->length) return NULL;
    void* removed = malloc((size_t)a->elem_size);
    if (!removed) return NULL;
    memcpy(removed, (char*)a->data + idx * a->elem_size, (size_t)a->elem_size);
    memmove((char*)a->data + idx * a->elem_size,
            (char*)a->data + (idx + 1) * a->elem_size,
            (size_t)((a->length - idx - 1) * a->elem_size));
    a->length--;
    return removed;
}

/* contains (int): 1 if val is present, 0 otherwise. */
int64_t haki_array_contains_int(HakiArray* a, int64_t val) {
    if (!a) return 0;
    for (int64_t i = 0; i < a->length; i++) {
        if (*(int64_t*)((char*)a->data + i * a->elem_size) == val) return 1;
    }
    return 0;
}

/* contains (string): 1 if val is present, 0 otherwise. */
int64_t haki_array_contains_str(HakiArray* a, const char* val) {
    if (!a || !val) return 0;
    for (int64_t i = 0; i < a->length; i++) {
        const char* e = *(const char**)((char*)a->data + i * a->elem_size);
        if (e && strcmp(e, val) == 0) return 1;
    }
    return 0;
}

/* indexOf (int): returns first index == val, or -1. */
int64_t haki_array_index_of_int(HakiArray* a, int64_t val) {
    if (!a) return -1;
    for (int64_t i = 0; i < a->length; i++) {
        if (*(int64_t*)((char*)a->data + i * a->elem_size) == val) return i;
    }
    return -1;
}

/* indexOf (string): returns first index matching val, or -1. */
int64_t haki_array_index_of_str(HakiArray* a, const char* val) {
    if (!a || !val) return -1;
    for (int64_t i = 0; i < a->length; i++) {
        const char* e = *(const char**)((char*)a->data + i * a->elem_size);
        if (e && strcmp(e, val) == 0) return i;
    }
    return -1;
}

/* first / last: pointer to first/last element slot. NULL if empty. */
void* haki_array_first(HakiArray* a) {
    return (a && a->length > 0) ? a->data : NULL;
}
void* haki_array_last(HakiArray* a) {
    return (a && a->length > 0)
        ? (char*)a->data + (a->length - 1) * a->elem_size : NULL;
}

/* join: concatenate string array with separator. Caller owns the result. */
const char* haki_array_join(HakiArray* a, const char* sep) {
    if (!a || a->length == 0) return strdup("");
    if (!sep) sep = "";
    size_t sep_len = strlen(sep), total = 0;
    for (int64_t i = 0; i < a->length; i++) {
        const char* e = *(const char**)((char*)a->data + i * a->elem_size);
        if (e) total += strlen(e);
        if (i < a->length - 1) total += sep_len;
    }
    char* r = (char*)malloc(total + 1); char* p = r;
    for (int64_t i = 0; i < a->length; i++) {
        const char* e = *(const char**)((char*)a->data + i * a->elem_size);
        if (e) { size_t l = strlen(e); memcpy(p, e, l); p += l; }
        if (i < a->length - 1) { memcpy(p, sep, sep_len); p += sep_len; }
    }
    *p = '\0'; return r;
}

/* ── Map<K, V> ──────────────────────────────────────────────────────
   Open-addressing hash map with string keys (v0.1).
   Values are stored as opaque byte blobs of fixed elem_size.
   String keys are copied and owned by the map.               */

#define HAKI_MAP_INIT_CAP 16

typedef struct HakiMapEntry {
    char*  key;     /* heap-owned copy; NULL = empty slot */
    void*  value;   /* heap-owned value bytes             */
} HakiMapEntry;

typedef struct {
    HakiMapEntry* entries;
    int64_t       capacity;
    int64_t       length;   /* number of live entries */
    int64_t       val_size; /* sizeof(V) in bytes     */
    char**        order;    /* insertion-order key list */
    int64_t       order_len;
    int64_t       order_cap;
} HakiMap;

static uint64_t haki_fnv1a(const char* s) {
    uint64_t h = 14695981039346656037ULL;
    while (*s) { h ^= (uint8_t)*s++; h *= 1099511628211ULL; }
    return h;
}

HakiMap* haki_map_new(int64_t val_size) {
    HakiMap* m = (HakiMap*)calloc(1, sizeof(HakiMap));
    if (!m) abort();
    m->val_size   = val_size;
    m->capacity   = HAKI_MAP_INIT_CAP;
    m->entries    = (HakiMapEntry*)calloc((size_t)m->capacity, sizeof(HakiMapEntry));
    if (!m->entries) abort();
    m->order_cap  = 8;
    m->order_len  = 0;
    m->order      = (char**)malloc(8 * sizeof(char*));
    if (!m->order) abort();
    return m;
}

static void haki_map_insert_entry(HakiMap* m, char* key, void* val) {
    uint64_t idx = haki_fnv1a(key) % (uint64_t)m->capacity;
    for (int64_t i = 0; i < m->capacity; i++) {
        int64_t slot = (int64_t)((idx + (uint64_t)i) % (uint64_t)m->capacity);
        HakiMapEntry* e = &m->entries[slot];
        if (!e->key) {
            e->key   = key;
            e->value = val;  /* store tagged pointer directly */
            m->length++;
            return;
        }
        if (strcmp(e->key, key) == 0) {
            e->value = val;  /* overwrite — do NOT free old (it's a tagged pointer) */
            free(key); /* duplicate key — discard */
            return;
        }
    }
    abort(); /* should never happen if load < 0.75 */
}

static void haki_map_grow(HakiMap* m) {
    int64_t old_cap = m->capacity;
    HakiMapEntry* old = m->entries;
    m->capacity *= 2;
    m->length   = 0;
    m->entries  = (HakiMapEntry*)calloc((size_t)m->capacity, sizeof(HakiMapEntry));
    if (!m->entries) abort();
    for (int64_t i = 0; i < old_cap; i++) {
        if (old[i].key) haki_map_insert_entry(m, old[i].key, old[i].value);
    }
    free(old);
}

void haki_map_set(HakiMap* m, const char* key, void* val_ptr) {
    if (!m || !key) return;
    /* Track insertion order for new keys */
    int already_ordered = 0;
    for (int64_t i = 0; i < m->order_len; i++) {
        if (strcmp(m->order[i], key) == 0) { already_ordered = 1; break; }
    }
    if (!already_ordered) {
        if (m->order_len >= m->order_cap) {
            m->order_cap *= 2;
            m->order = (char**)realloc(m->order, (size_t)m->order_cap * sizeof(char*));
            if (!m->order) abort();
        }
        m->order[m->order_len++] = strdup(key);
    }
    if (m->length * 4 >= m->capacity * 3) haki_map_grow(m);
    char* k = strdup(key);
    if (!k) abort();
    /* val_ptr is already a tagged void* — store it directly, no memcpy */
    haki_map_insert_entry(m, k, val_ptr);
}

/* Returns pointer to value, or NULL if not found. */
void* haki_map_get(HakiMap* m, const char* key) {
    if (!m || !key || m->length == 0) return NULL;
    uint64_t idx = haki_fnv1a(key) % (uint64_t)m->capacity;
    for (int64_t i = 0; i < m->capacity; i++) {
        int64_t slot = (int64_t)((idx + (uint64_t)i) % (uint64_t)m->capacity);
        HakiMapEntry* e = &m->entries[slot];
        if (!e->key) return NULL; /* empty slot = not found */
        if (strcmp(e->key, key) == 0) return e->value;
    }
    return NULL;
}

int8_t haki_map_has(HakiMap* m, const char* key) {
    return haki_map_get(m, key) != NULL ? 1 : 0;
}

void haki_map_delete(HakiMap* m, const char* key) {
    if (!m || !key) return;
    /* Remove from insertion-order list */
    for (int64_t i = 0; i < m->order_len; i++) {
        if (strcmp(m->order[i], key) == 0) {
            free(m->order[i]);
            memmove(&m->order[i], &m->order[i+1],
                    (size_t)(m->order_len - i - 1) * sizeof(char*));
            m->order_len--;
            break;
        }
    }
    uint64_t idx = haki_fnv1a(key) % (uint64_t)m->capacity;
    for (int64_t i = 0; i < m->capacity; i++) {
        int64_t slot = (int64_t)((idx + (uint64_t)i) % (uint64_t)m->capacity);
        HakiMapEntry* e = &m->entries[slot];
        if (!e->key) return;
        if (strcmp(e->key, key) == 0) {
            free(e->key);  e->key = NULL;
            e->value = NULL;  /* do NOT free — it's a tagged pointer, not heap data */
            m->length--;
            return;
        }
    }
}

/* Returns a HakiArray* of string keys (each stored as void* = const char*) */
HakiArray* haki_map_keys(HakiMap* m) {
    HakiArray* arr = haki_array_new(sizeof(void*));
    if (!m) return arr;
    for (int64_t i = 0; i < m->capacity; i++) {
        if (m->entries[i].key) {
            void* key_ptr = (void*)m->entries[i].key;
            haki_array_append(arr, &key_ptr);
        }
    }
    return arr;
}

int64_t haki_map_length(HakiMap* m) { return m ? m->length : 0; }

/* getOrDefault: returns pointer to value if found, else pointer to default. */
void* haki_map_get_or_default(HakiMap* m, const char* key, void* default_val) {
    void* found = haki_map_get(m, key);
    return found ? found : default_val;
}

void haki_map_free(HakiMap* m) {
    if (!m) return;
    for (int64_t i = 0; i < m->capacity; i++) {
        if (m->entries[i].key) free(m->entries[i].key);
        /* do NOT free values — they are tagged pointers, not owned heap data */
    }
    free(m->entries);
    for (int64_t i = 0; i < m->order_len; i++) free(m->order[i]);
    free(m->order);
    free(m);
}

/* Returns HakiArray* of string keys in insertion order */
HakiArray* haki_map_ordered_keys(HakiMap* m) {
    HakiArray* arr = haki_array_new(sizeof(void*));
    if (!m) return arr;
    for (int64_t i = 0; i < m->order_len; i++) {
        void* kp = (void*)m->order[i];
        haki_array_append(arr, &kp);
    }
    return arr;
}

/* ── Thread (OS 1:1 pthread wrapper) ────────────────────────────── */

#include <pthread.h>

typedef struct {
    pthread_t tid;
} HakiThread;

HakiThread* haki_thread_spawn(void (*fn)(void)) {
    HakiThread* t = (HakiThread*)malloc(sizeof(HakiThread));
    if (!t) abort();
    /* pthread entry must be void* (*)(void*); wrap the no-arg fn */
    typedef void* (*pthread_fn)(void*);
    if (pthread_create(&t->tid, NULL, (pthread_fn)(void*)fn, NULL) != 0) {
        fprintf(stderr, "haki: thread_spawn failed\n");
        abort();
    }
    return t;
}

void haki_thread_join(HakiThread* t) {
    if (!t) return;
    pthread_join(t->tid, NULL);
    free(t);
}

/* ── Task<T> — call-site async + thread pool ─────────────────────
   haki_task_spawn(fn, arg) → HakiTask*
     Submits fn(arg) to the global thread pool. Returns a Task handle.
   haki_task_await(task) → void*
     Blocks until complete, returns the result pointer.
   haki_task_detach(task)
     Drops the user handle — task runs to completion in background.  */

#define HAKI_POOL_THREADS 8
#define HAKI_QUEUE_CAP    256

typedef void* (*HakiTaskFn)(void*);

typedef struct {
    _Atomic int64_t refcount;
    HakiTaskFn      fn;
    void*           arg;
    void*           result;
    int8_t          done;
    pthread_mutex_t done_mu;
    pthread_cond_t  done_cond;
} HakiTask;

static struct {
    pthread_t       threads[HAKI_POOL_THREADS];
    HakiTask*       queue[HAKI_QUEUE_CAP];
    int             head, tail, size;
    pthread_mutex_t mu;
    pthread_cond_t  cond;
    int             running;
} haki_pool_g;

static void haki_task_deref(HakiTask* t) {
    if (!t) return;
    if (atomic_fetch_sub_explicit(&t->refcount, 1, memory_order_acq_rel) == 1) {
        pthread_mutex_destroy(&t->done_mu);
        pthread_cond_destroy(&t->done_cond);
        free(t);
    }
}

static void* haki_pool_worker(void* unused) {
    (void)unused;
    for (;;) {
        pthread_mutex_lock(&haki_pool_g.mu);
        while (haki_pool_g.size == 0)
            pthread_cond_wait(&haki_pool_g.cond, &haki_pool_g.mu);
        HakiTask* t = haki_pool_g.queue[haki_pool_g.head];
        haki_pool_g.head = (haki_pool_g.head + 1) % HAKI_QUEUE_CAP;
        haki_pool_g.size--;
        pthread_mutex_unlock(&haki_pool_g.mu);

        void* res = t->fn(t->arg);

        pthread_mutex_lock(&t->done_mu);
        t->result = res;
        t->done   = 1;
        pthread_cond_broadcast(&t->done_cond);
        pthread_mutex_unlock(&t->done_mu);

        haki_task_deref(t); /* release executor reference */
    }
    return NULL;
}

static void haki_pool_ensure_started(void) {
    if (haki_pool_g.running) return;
    pthread_mutex_init(&haki_pool_g.mu, NULL);
    pthread_cond_init(&haki_pool_g.cond, NULL);
    for (int i = 0; i < HAKI_POOL_THREADS; i++)
        pthread_create(&haki_pool_g.threads[i], NULL, haki_pool_worker, NULL);
    haki_pool_g.running = 1;
}

HakiTask* haki_task_spawn(HakiTaskFn fn, void* arg) {
    haki_pool_ensure_started();
    HakiTask* t = (HakiTask*)calloc(1, sizeof(HakiTask));
    if (!t) abort();
    atomic_store_explicit(&t->refcount, 2, memory_order_relaxed); /* user + executor */
    t->fn  = fn;
    t->arg = arg;
    pthread_mutex_init(&t->done_mu, NULL);
    pthread_cond_init(&t->done_cond, NULL);

    pthread_mutex_lock(&haki_pool_g.mu);
    if (haki_pool_g.size >= HAKI_QUEUE_CAP) {
        pthread_mutex_unlock(&haki_pool_g.mu);
        fprintf(stderr, "haki: task queue full\n");
        abort();
    }
    haki_pool_g.queue[haki_pool_g.tail] = t;
    haki_pool_g.tail = (haki_pool_g.tail + 1) % HAKI_QUEUE_CAP;
    haki_pool_g.size++;
    pthread_cond_signal(&haki_pool_g.cond);
    pthread_mutex_unlock(&haki_pool_g.mu);
    return t;
}

void* haki_task_await(HakiTask* t) {
    if (!t) return NULL;
    pthread_mutex_lock(&t->done_mu);
    while (!t->done)
        pthread_cond_wait(&t->done_cond, &t->done_mu);
    void* res = t->result;
    pthread_mutex_unlock(&t->done_mu);
    haki_task_deref(t); /* release user reference */
    return res;
}

void haki_task_detach(HakiTask* t) {
    haki_task_deref(t); /* release user reference; executor ref keeps it alive */
}

/* ── Mutex<T> ────────────────────────────────────────────────────── */

typedef struct {
    pthread_mutex_t mu;
    void*           value;
} HakiMutex;

typedef struct {
    HakiMutex* mutex;
    void*      value;
} HakiMutexGuard;

HakiMutex* haki_mutex_new(void* initial) {
    HakiMutex* m = (HakiMutex*)malloc(sizeof(HakiMutex));
    if (!m) abort();
    pthread_mutex_init(&m->mu, NULL);
    m->value = initial;
    return m;
}

HakiMutexGuard* haki_mutex_lock(HakiMutex* m) {
    pthread_mutex_lock(&m->mu);
    HakiMutexGuard* g = (HakiMutexGuard*)malloc(sizeof(HakiMutexGuard));
    if (!g) abort();
    g->mutex = m;
    g->value = m->value;
    return g;
}

void haki_mutex_unlock(HakiMutexGuard* g) {
    if (!g) return;
    pthread_mutex_unlock(&g->mutex->mu);
    free(g);
}

void haki_mutex_free(HakiMutex* m) {
    if (!m) return;
    pthread_mutex_destroy(&m->mu);
    free(m);
}

/* ── String methods ──────────────────────────────────────────────
   All string operations work on null-terminated C strings (const char*).
   Functions that return new strings heap-allocate via malloc.
   The caller owns the result.                                     */

#include <ctype.h>

/* s.split(sep) → Array<string> (HakiArray* of char* elements) */
HakiArray* haki_string_split(const char* s, const char* sep) {
    HakiArray* arr = haki_array_new(sizeof(char*));
    if (!s || !sep || sep[0] == '\0') {
        char* dup = strdup(s ? s : "");
        haki_array_append(arr, &dup);
        return arr;
    }
    size_t sep_len = strlen(sep);
    const char* cur = s;
    while (1) {
        const char* found = strstr(cur, sep);
        size_t piece_len = found ? (size_t)(found - cur) : strlen(cur);
        char* piece = (char*)malloc(piece_len + 1);
        memcpy(piece, cur, piece_len);
        piece[piece_len] = '\0';
        haki_array_append(arr, &piece);
        if (!found) break;
        cur = found + sep_len;
    }
    return arr;
}

char* haki_string_trim(const char* s) {
    if (!s) return strdup("");
    while (isspace((unsigned char)*s)) s++;
    size_t len = strlen(s);
    while (len > 0 && isspace((unsigned char)s[len-1])) len--;
    char* r = (char*)malloc(len + 1);
    memcpy(r, s, len);
    r[len] = '\0';
    return r;
}

char* haki_string_trim_start(const char* s) {
    if (!s) return strdup("");
    while (isspace((unsigned char)*s)) s++;
    return strdup(s);
}

char* haki_string_trim_end(const char* s) {
    if (!s) return strdup("");
    size_t len = strlen(s);
    while (len > 0 && isspace((unsigned char)s[len-1])) len--;
    char* r = (char*)malloc(len + 1);
    memcpy(r, s, len);
    r[len] = '\0';
    return r;
}

char* haki_string_to_upper(const char* s) {
    if (!s) return strdup("");
    char* r = strdup(s);
    for (char* p = r; *p; p++) *p = (char)toupper((unsigned char)*p);
    return r;
}

char* haki_string_to_lower(const char* s) {
    if (!s) return strdup("");
    char* r = strdup(s);
    for (char* p = r; *p; p++) *p = (char)tolower((unsigned char)*p);
    return r;
}

int8_t haki_string_contains(const char* s, const char* sub) {
    if (!s || !sub) return 0;
    return strstr(s, sub) != NULL ? 1 : 0;
}

int8_t haki_string_starts_with(const char* s, const char* prefix) {
    if (!s || !prefix) return 0;
    return strncmp(s, prefix, strlen(prefix)) == 0 ? 1 : 0;
}

int8_t haki_string_ends_with(const char* s, const char* suffix) {
    if (!s || !suffix) return 0;
    size_t sl = strlen(s), fl = strlen(suffix);
    return (sl >= fl && strcmp(s + sl - fl, suffix) == 0) ? 1 : 0;
}

/* Replace FIRST occurrence of `from` with `to` in `s` */
char* haki_string_replace(const char* s, const char* from, const char* to) {
    if (!s || !from || from[0] == '\0') return strdup(s ? s : "");
    const char* found = strstr(s, from);
    if (!found) return strdup(s);
    size_t from_len = strlen(from);
    size_t to_len   = to ? strlen(to) : 0;
    size_t prefix   = (size_t)(found - s);
    size_t suffix   = strlen(found + from_len);
    char* result = (char*)malloc(prefix + to_len + suffix + 1);
    memcpy(result, s, prefix);
    if (to) memcpy(result + prefix, to, to_len);
    memcpy(result + prefix + to_len, found + from_len, suffix);
    result[prefix + to_len + suffix] = '\0';
    return result;
}

int64_t haki_string_index_of(const char* s, const char* sub) {
    if (!s || !sub) return -1;
    const char* found = strstr(s, sub);
    return found ? (int64_t)(found - s) : -1;
}

char* haki_string_substring(const char* s, int64_t start, int64_t end) {
    if (!s) return strdup("");
    int64_t len = (int64_t)strlen(s);
    if (start < 0) start = 0;
    if (end > len) end = len;
    if (start >= end) return strdup("");
    int64_t sub_len = end - start;
    char* r = (char*)malloc((size_t)sub_len + 1);
    memcpy(r, s + start, (size_t)sub_len);
    r[sub_len] = '\0';
    return r;
}

/* s.slice(start, end) — alias for substring */
char* haki_string_slice(const char* s, int64_t start, int64_t end) {
    return haki_string_substring(s, start, end);
}

/* s.charAt(i) — returns 1-char string at index i, or "" if out of range */
char* haki_string_char_at(const char* s, int64_t i) {
    if (!s) return strdup("");
    int64_t len = (int64_t)strlen(s);
    if (i < 0 || i >= len) return strdup("");
    char* r = (char*)malloc(2);
    r[0] = s[i];
    r[1] = '\0';
    return r;
}

/* s.charCodeAt(i) — returns Unicode code point (ASCII) at index i, or -1 */
int64_t haki_string_char_code_at(const char* s, int64_t i) {
    if (!s) return -1;
    int64_t len = (int64_t)strlen(s);
    if (i < 0 || i >= len) return -1;
    return (int64_t)(unsigned char)s[i];
}

/* s.padStart(width, padChar) — pad from left to reach width */
char* haki_string_pad_start(const char* s, int64_t width, const char* pad) {
    if (!s) s = "";
    if (!pad || pad[0] == '\0') pad = " ";
    int64_t slen = (int64_t)strlen(s);
    int64_t padlen = (int64_t)strlen(pad);
    if (slen >= width) return strdup(s);
    int64_t need = width - slen;
    char* r = (char*)malloc((size_t)width + 1);
    int64_t pos = 0;
    while (pos < need) {
        int64_t rem = need - pos;
        int64_t copy = (padlen < rem) ? padlen : rem;
        memcpy(r + pos, pad, (size_t)copy);
        pos += copy;
    }
    memcpy(r + need, s, (size_t)slen);
    r[width] = '\0';
    return r;
}

/* s.padEnd(width, padChar) — pad from right to reach width */
char* haki_string_pad_end(const char* s, int64_t width, const char* pad) {
    if (!s) s = "";
    if (!pad || pad[0] == '\0') pad = " ";
    int64_t slen = (int64_t)strlen(s);
    int64_t padlen = (int64_t)strlen(pad);
    if (slen >= width) return strdup(s);
    int64_t need = width - slen;
    char* r = (char*)malloc((size_t)width + 1);
    memcpy(r, s, (size_t)slen);
    int64_t pos = slen;
    while (pos < width) {
        int64_t rem = width - pos;
        int64_t copy = (padlen < rem) ? padlen : rem;
        memcpy(r + pos, pad, (size_t)copy);
        pos += copy;
    }
    r[width] = '\0';
    return r;
}

/* ── File I/O ────────────────────────────────────────────────────
   Simple blocking file operations for scripting use.             */

void haki_file_read(const char* path, char** out_content, char** out_error) {
    *out_content = NULL;
    *out_error   = NULL;
    FILE* f = fopen(path, "rb");
    if (!f) { *out_error = strdup(strerror(errno)); return; }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    rewind(f);
    if (size < 0) { fclose(f); *out_error = strdup("seek failed"); return; }
    char* buf = (char*)malloc((size_t)size + 1);
    if (!buf) { fclose(f); *out_error = strdup("out of memory"); return; }
    size_t n = fread(buf, 1, (size_t)size, f);
    fclose(f);
    buf[n] = '\0';
    *out_content = buf;
}

/* haki_read_file — single-return wrapper matching C emitter's calling convention.
 * Returns a heap-allocated void* pair { content_ptr, error_ptr } matching
 * readFile(path) -> (string, Error?) semantics.
 * Uses raw void* fields to avoid forward-declaration dependency on HakiError/__Tuple2. */
void* haki_read_file(const char* path) {
    char* content = NULL;
    char* err_msg = NULL;
    haki_file_read(path, &content, &err_msg);
    /* Allocate a simple two-pointer tuple: [content, error] */
    void** t = (void**)malloc(2 * sizeof(void*));
    t[0] = (void*)(content ? content : (char*)"");
    if (err_msg) {
        /* Allocate a minimal error object: [arc_count, message] */
        void** e = (void**)malloc(2 * sizeof(void*));
        int64_t* arc = (int64_t*)malloc(sizeof(int64_t));
        *arc = 1;
        e[0] = (void*)arc;
        e[1] = (void*)err_msg;
        t[1] = (void*)e;
    } else {
        t[1] = NULL;
    }
    return (void*)t;
}

/* haki_write_file — matches C emitter's calling convention for writeFile(). */
void* haki_write_file(const char* path, const char* content) {
    /* Forward declaration needed — haki_file_write is defined below */
    char* haki_file_write(const char*, const char*);
    char* err = haki_file_write(path, content);
    if (!err) return NULL;
    /* Return error as a simple two-pointer [arc, message] object */
    void** e = (void**)malloc(2 * sizeof(void*));
    int64_t* arc = (int64_t*)malloc(sizeof(int64_t));
    *arc = 1;
    e[0] = (void*)arc;
    e[1] = (void*)err;
    return (void*)e;
}

char* haki_file_write(const char* path, const char* content) {
    FILE* f = fopen(path, "wb");
    if (!f) return strdup(strerror(errno));
    size_t len = content ? strlen(content) : 0;
    size_t n = fwrite(content, 1, len, f);
    fclose(f);
    if (n != len) return strdup("write failed");
    return NULL;
}

int8_t haki_file_exists(const char* path) {
    FILE* f = fopen(path, "rb");
    if (f) { fclose(f); return 1; }
    return 0;
}

/* ── Command-line arguments ──────────────────────────────────────────────── */

static int   _haki_argc = 0;
static char** _haki_argv = NULL;

void haki_runtime_init(int argc, char** argv) {
    _haki_argc = argc;
    _haki_argv = argv;
}

/* argv() -> Array<string>: returns program arguments as a Haki array. */
void* haki_argv(void) {
    void* arr = haki_array_new(sizeof(void*));
    for (int i = 0; i < _haki_argc; i++) {
        char* s = strdup(_haki_argv[i]);
        haki_array_append(arr, &s);  /* pass pointer-to-pointer; append copies sizeof(void*) bytes */
    }
    return arr;
}

/* ── std/env, std/time, std/process, std/regex ───────────────────────────── */
/* Forward declaration — haki_error_new is defined in the Error section below */
void* haki_error_new(const char* message);

#ifndef _WIN32
#include <unistd.h>   /* getcwd, chdir, setenv, unsetenv */
#include <errno.h>
#include <dirent.h>   /* opendir, readdir, closedir */
#include <sys/stat.h> /* mkdir */
#endif

/* ── std/env ─────────────────────────────────────────────────────────────── */

void* haki_env_get(const char* name) {
    const char* val = getenv(name);
    if (!val) {
        void* err = haki_error_new("environment variable not set");
        void** result = (void**)malloc(2 * sizeof(void*));
        result[0] = (void*)strdup("");
        result[1] = err;
        return (void*)result;
    }
    void** result = (void**)malloc(2 * sizeof(void*));
    result[0] = (void*)strdup(val);
    result[1] = NULL;
    return (void*)result;
}

void* haki_env_set(const char* name, const char* value) {
#ifdef _WIN32
    if (_putenv_s(name, value) != 0)
        return haki_error_new("failed to set environment variable");
#else
    if (setenv(name, value, 1) != 0)
        return haki_error_new(strerror(errno));
#endif
    return NULL;
}

void* haki_env_unset(const char* name) {
#ifdef _WIN32
    _putenv_s(name, "");
#else
    unsetenv(name);
#endif
    return NULL;
}

void* haki_env_cwd(void) {
    char buf[4096];
#ifdef _WIN32
    if (!_getcwd(buf, sizeof(buf))) {
#else
    if (!getcwd(buf, sizeof(buf))) {
#endif
        void** r = (void**)malloc(2 * sizeof(void*));
        r[0] = (void*)strdup("");
        r[1] = haki_error_new(strerror(errno));
        return (void*)r;
    }
    void** r = (void**)malloc(2 * sizeof(void*));
    r[0] = (void*)strdup(buf);
    r[1] = NULL;
    return (void*)r;
}

void* haki_env_chdir(const char* path) {
#ifdef _WIN32
    if (_chdir(path) != 0)
#else
    if (chdir(path) != 0)
#endif
        return haki_error_new(strerror(errno));
    return NULL;
}

/* ── std/time ────────────────────────────────────────────────────────────── */

#include <time.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <sys/time.h>
#endif

int64_t haki_time_now_ms(void) {
#ifdef _WIN32
    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    ULONGLONG t = ((ULONGLONG)ft.dwHighDateTime << 32) | ft.dwLowDateTime;
    return (int64_t)((t - 116444736000000000ULL) / 10000);
#else
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return (int64_t)tv.tv_sec * 1000LL + tv.tv_usec / 1000LL;
#endif
}

void haki_time_sleep_ms(int64_t ms) {
    if (ms <= 0) return;
#ifdef _WIN32
    Sleep((DWORD)ms);
#else
    struct timespec ts;
    ts.tv_sec  = ms / 1000;
    ts.tv_nsec = (ms % 1000) * 1000000L;
    nanosleep(&ts, NULL);
#endif
}

const char* haki_time_format(int64_t unix_sec) {
    time_t t = (time_t)unix_sec;
    struct tm* tm_info = gmtime(&t);
    char* buf = (char*)malloc(32);
    strftime(buf, 32, "%Y-%m-%dT%H:%M:%SZ", tm_info);
    return buf;
}

/* ── time module wrappers (time__*) ─────────────────────────────────────── */

int64_t time__now(void)               { return haki_time_now_ms(); }
void    time__sleep(int64_t ms)       { haki_time_sleep_ms(ms); }
const char* time__format(int64_t sec) { return haki_time_format(sec); }
const char* time__formatPattern(int64_t sec, const char* pat) {
    time_t t = (time_t)sec;
    struct tm* tm_info = gmtime(&t);
    char* buf = (char*)malloc(128);
    strftime(buf, 128, pat, tm_info);
    return buf;
}
/* alias used by some codegen paths */
const char* haki_time_format_pattern(int64_t sec, const char* pat) {
    return time__formatPattern(sec, pat);
}

/* ── std/process ─────────────────────────────────────────────────────────── */

#include <stdio.h>

/* run: capture stdout, return as string */
void* haki_process_run(const char* cmd, void* args_arr) {
    /* Build command string from cmd + args array */
    char buf[4096];
    int64_t len = haki_array_length(args_arr);
    snprintf(buf, sizeof(buf), "%s", cmd);
    for (int64_t i = 0; i < len; i++) {
        const char* arg = *(const char**)haki_array_get(args_arr, i);
        strncat(buf, " ", sizeof(buf) - strlen(buf) - 1);
        strncat(buf, arg, sizeof(buf) - strlen(buf) - 1);
    }
#ifdef _WIN32
    FILE* fp = _popen(buf, "r");
#else
    FILE* fp = popen(buf, "r");
#endif
    if (!fp) {
        void** r = (void**)malloc(2 * sizeof(void*));
        r[0] = (void*)strdup("");
        r[1] = haki_error_new("failed to run command");
        return (void*)r;
    }
    /* Read stdout */
    char out[65536]; out[0] = '\0';
    char line[1024];
    while (fgets(line, sizeof(line), fp)) {
        strncat(out, line, sizeof(out) - strlen(out) - 1);
    }
    int status;
#ifdef _WIN32
    status = _pclose(fp);
#else
    status = pclose(fp);
#endif
    void** r = (void**)malloc(2 * sizeof(void*));
    if (status != 0) {
        r[0] = (void*)strdup(out);
        r[1] = haki_error_new("command exited with non-zero status");
    } else {
        r[0] = (void*)strdup(out);
        r[1] = NULL;
    }
    return (void*)r;
}

/* exec: inherit stdio, return exit code */
void* haki_process_exec(const char* cmd, void* args_arr) {
    char buf[4096];
    int64_t len = haki_array_length(args_arr);
    snprintf(buf, sizeof(buf), "%s", cmd);
    for (int64_t i = 0; i < len; i++) {
        const char* arg = *(const char**)haki_array_get(args_arr, i);
        strncat(buf, " ", sizeof(buf) - strlen(buf) - 1);
        strncat(buf, arg, sizeof(buf) - strlen(buf) - 1);
    }
    int code = system(buf);
    void** r = (void**)malloc(2 * sizeof(void*));
    int64_t* code_ptr = (int64_t*)malloc(sizeof(int64_t));
    *code_ptr = (int64_t)code;
    r[0] = (void*)code_ptr;
    r[1] = NULL;
    return (void*)r;
}

/* shell: run via /bin/sh -c, capture output */
void* haki_process_shell(const char* cmd) {
#ifdef _WIN32
    FILE* fp = _popen(cmd, "r");
#else
    FILE* fp = popen(cmd, "r");
#endif
    if (!fp) {
        void** r = (void**)malloc(2 * sizeof(void*));
        r[0] = (void*)strdup("");
        r[1] = haki_error_new("failed to run shell command");
        return (void*)r;
    }
    char out[65536]; out[0] = '\0';
    char line[1024];
    while (fgets(line, sizeof(line), fp)) {
        strncat(out, line, sizeof(out) - strlen(out) - 1);
    }
#ifdef _WIN32
    _pclose(fp);
#else
    pclose(fp);
#endif
    void** r = (void**)malloc(2 * sizeof(void*));
    r[0] = (void*)strdup(out);
    r[1] = NULL;
    return (void*)r;
}

void haki_process_exit(int64_t code) {
    exit((int)code);
}

/* ── std/regex ───────────────────────────────────────────────────────────── */

#include <regex.h>

int8_t haki_regex_matches(const char* s, const char* pattern) {
    regex_t re;
    if (regcomp(&re, pattern, REG_EXTENDED | REG_NOSUB) != 0) return 0;
    int match = regexec(&re, s, 0, NULL, 0);
    regfree(&re);
    return match == 0 ? 1 : 0;
}

void* haki_regex_find(const char* s, const char* pattern) {
    regex_t re;
    void** r = (void**)malloc(2 * sizeof(void*));
    if (regcomp(&re, pattern, REG_EXTENDED) != 0) {
        r[0] = (void*)strdup("");
        r[1] = haki_error_new("invalid regex pattern");
        return (void*)r;
    }
    regmatch_t match;
    if (regexec(&re, s, 1, &match, 0) == 0) {
        int len = match.rm_eo - match.rm_so;
        char* found = (char*)malloc(len + 1);
        strncpy(found, s + match.rm_so, len);
        found[len] = '\0';
        r[0] = (void*)found;
        r[1] = NULL;
    } else {
        r[0] = (void*)strdup("");
        r[1] = haki_error_new("no match found");
    }
    regfree(&re);
    return (void*)r;
}

const char* haki_regex_replace_all(const char* s, const char* pattern, const char* replacement) {
    regex_t re;
    if (regcomp(&re, pattern, REG_EXTENDED) != 0) return strdup(s);
    /* Allocate generous output buffer */
    size_t outsize = strlen(s) * 4 + 1024;
    char* out = (char*)malloc(outsize);
    out[0] = '\0';
    const char* cur = s;
    regmatch_t match;
    while (*cur && regexec(&re, cur, 1, &match, 0) == 0) {
        /* Append text before match */
        strncat(out, cur, match.rm_so);
        /* Append replacement */
        strncat(out, replacement, outsize - strlen(out) - 1);
        cur += match.rm_eo;
        if (match.rm_eo == 0) { /* zero-width match guard */
            if (*cur) { char c[2] = {*cur, '\0'}; strncat(out, c, 1); cur++; }
            else break;
        }
    }
    strncat(out, cur, outsize - strlen(out) - 1);
    regfree(&re);
    return out;
}

void* haki_regex_split(const char* s, const char* pattern) {
    regex_t re;
    void* arr = haki_array_new(sizeof(void*));
    if (regcomp(&re, pattern, REG_EXTENDED) != 0) {
        char* copy = strdup(s);
        haki_array_append(arr, &copy);
        return arr;
    }
    const char* cur = s;
    regmatch_t match;
    while (*cur && regexec(&re, cur, 1, &match, 0) == 0) {
        if (match.rm_so > 0) {
            char* part = (char*)malloc(match.rm_so + 1);
            strncpy(part, cur, match.rm_so);
            part[match.rm_so] = '\0';
            haki_array_append(arr, &part);
        }
        cur += match.rm_eo;
        if (match.rm_eo == 0) { if (*cur) cur++; else break; }
    }
    if (*cur) {
        char* rest = strdup(cur);
        haki_array_append(arr, &rest);
    }
    regfree(&re);
    return arr;
}

typedef struct {
    void*       __arc;    /* ARC header — must be first */
    const char* message;
    void*       cause;    /* Error? — null if no cause */
} HakiError;

void* haki_error_new(const char* message) {
    HakiError* e = (HakiError*)haki_alloc(sizeof(HakiError));
    e->message = message ? strdup(message) : "";
    e->cause   = NULL;
    return (void*)e;
}

void* haki_error_new_with_cause(const char* message, void* cause) {
    HakiError* e = (HakiError*)haki_alloc(sizeof(HakiError));
    e->message = message ? strdup(message) : "";
    e->cause   = cause;
    return (void*)e;
}

void* haki_error_wrap(const char* message) {
    if (!message) return NULL;
    return haki_error_new(message);
}

const char* haki_error_message(void* err) {
    if (!err) return "";
    return ((HakiError*)err)->message;
}

void* haki_error_cause(void* err) {
    if (!err) return NULL;
    return ((HakiError*)err)->cause;
}


/* ── Math functions ──────────────────────────────────────────────────────────── */

#include <math.h>

double haki_math_sqrt(double x) { return sqrt(x); }
double haki_math_floor(double x) { return floor(x); }
double haki_math_ceil(double x) { return ceil(x); }
double haki_math_round(double x) { return round(x); }
double haki_math_pow_f(double base, double exp) { return pow(base, exp); }
double haki_math_log(double x) { return log(x); }
double haki_math_sin(double x) { return sin(x); }
double haki_math_cos(double x) { return cos(x); }
double haki_math_abs_f(double x) { return fabs(x); }
int64_t haki_math_floor_to_int(double x) { return (int64_t)floor(x); }
int64_t haki_math_ceil_to_int(double x) { return (int64_t)ceil(x); }
int64_t haki_math_round_to_int(double x) { return (int64_t)round(x); }

/* ── Process args (argv[1..], excluding program name) ───────────────────────── */

/* args() -> Array<string>: returns user-provided arguments (skips argv[0]) */
void* haki_process_args(void) {
    void* arr = haki_array_new(sizeof(void*));
    for (int i = 1; i < _haki_argc; i++) {
        char* s = strdup(_haki_argv[i]);
        haki_array_append(arr, &s);
    }
    return arr;
}

/* pid() -> int: returns the current process ID */
int64_t haki_getpid(void) {
#ifdef _WIN32
    return (int64_t)_getpid();
#else
    return (int64_t)getpid();
#endif
}

/* ── Shell command execution ─────────────────────────────────────────────────── */

int64_t haki_run_cmd(const char* cmd) {
    if (!cmd) return -1;
    return (int64_t)system(cmd);
}

/* Bootstrap compatibility alias: hakic_s4-compiled code calls runCmd() directly */
int64_t runCmd(const char* cmd) {
    if (!cmd) return -1;
    return (int64_t)system(cmd);
}

/* HTTP server: excluded from bootstrap runtime */

/* ── Stdlib module wrappers (math__, strings__, fs__, env__, process__) ──────── */

/* math module */
int64_t math__abs(int64_t x)                    { return x < 0 ? -x : x; }
int64_t math__max(int64_t a, int64_t b)         { return a > b ? a : b; }
int64_t math__min(int64_t a, int64_t b)         { return a < b ? a : b; }
int64_t math__clamp(int64_t v, int64_t lo, int64_t hi) {
    if (v < lo) return lo; if (v > hi) return hi; return v;
}
int64_t math__pow(int64_t base, int64_t exp) {
    int64_t r = 1;
    for (int64_t i = 0; i < exp; i++) r *= base;
    return r;
}
double  math__sqrt(double x)   { return sqrt(x); }
int64_t math__floor(double x)  { return (int64_t)floor(x); }
int64_t math__ceil(double x)   { return (int64_t)ceil(x); }
int64_t math__round(double x)  { return (int64_t)round(x); }
double  math__log(double x)    { return log(x); }
double  math__sin(double x)    { return sin(x); }
double  math__cos(double x)    { return cos(x); }
double  math__abs_f(double x)  { return fabs(x); }

/* strings module */
char* strings__repeat(const char* s, int64_t n) {
    if (!s || n <= 0) return strdup("");
    size_t slen = strlen(s);
    size_t total = (size_t)n * slen;
    char* r = (char*)malloc(total + 1);
    for (int64_t i = 0; i < n; i++) memcpy(r + (size_t)i * slen, s, slen);
    r[total] = '\0';
    return r;
}
int64_t strings__count(const char* s, const char* sub) {
    if (!s || !sub || sub[0] == '\0') return 0;
    int64_t count = 0;
    size_t sublen = strlen(sub);
    const char* cur = s;
    while ((cur = strstr(cur, sub)) != NULL) { count++; cur += sublen; }
    return count;
}
char* strings__join(void* arr, const char* sep) {
    if (!arr) return strdup("");
    HakiArray* a = (HakiArray*)arr;
    int64_t len = haki_array_length(a);
    if (len == 0) return strdup("");
    size_t seplen = sep ? strlen(sep) : 0;
    size_t total = 0;
    for (int64_t i = 0; i < len; i++) {
        const char* s = *(const char**)haki_array_get(a, i);
        if (s) total += strlen(s);
        if (i < len - 1) total += seplen;
    }
    char* result = (char*)malloc(total + 1);
    size_t pos = 0;
    for (int64_t i = 0; i < len; i++) {
        const char* s = *(const char**)haki_array_get(a, i);
        if (s) { size_t sl = strlen(s); memcpy(result + pos, s, sl); pos += sl; }
        if (i < len - 1 && sep) { memcpy(result + pos, sep, seplen); pos += seplen; }
    }
    result[pos] = '\0';
    return result;
}
char* strings__toUpper(const char* s) { return haki_string_to_upper(s); }
char* strings__toLower(const char* s) { return haki_string_to_lower(s); }
int64_t strings__length(const char* s) { return haki_string_length(s); }

/* fs module */
char*   fs__read(const char* path) {
    /* haki_read_file returns a (string, Error?) tuple — extract just the string */
    void** t = (void**)haki_read_file(path);
    return t ? (char*)t[0] : (char*)"";
}
void*   fs__write(const char* path, const char* c)   { return haki_write_file(path, c); }
int8_t  fs__exists(const char* path)                 { return haki_file_exists(path); }
void*   fs__delete(const char* path) {
    if (!path) return NULL;
    remove(path);
    rmdir(path);
    return NULL;
}
void*   fs__mkdir(const char* path) {
#ifdef _WIN32
    _mkdir(path);
#else
    mkdir(path, 0755);
#endif
    return NULL;
}
void*   fs__readDir(const char* path) {
    void* arr = haki_array_new(sizeof(void*));
#ifndef _WIN32
    DIR* d = opendir(path);
    if (!d) return arr;
    struct dirent* entry;
    while ((entry = readdir(d)) != NULL) {
        if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0) continue;
        char* name = strdup(entry->d_name);
        haki_array_append(arr, &name);
    }
    closedir(d);
#endif
    return arr;
}

/* env module */
/* env__get: return the string value or NULL (not the (string, Error?) tuple) */
const char* env__get(const char* name) {
    const char* val = getenv(name);
    return val ? strdup(val) : NULL;
}
void*   env__set(const char* name, const char* val)  { return haki_env_set(name, val); }
void*   env__unset(const char* name)                 { return haki_env_unset(name); }
void*   env__cwd(void)                               { return haki_env_cwd(); }

/* process module */
void*   process__args(void)                          { return haki_process_args(); }
void    process__exit(int64_t code)                  { haki_process_exit(code); }
int64_t process__pid(void)                           { return haki_getpid(); }
void*   process__run(const char* cmd, void* args)    { return haki_process_run(cmd, args); }
void*   process__shell(const char* cmd)              { return haki_process_shell(cmd); }

/* ── CSV module ──────────────────────────────────────────────────────────────── */

/* csv__parse: parse CSV text into Array<Array<string>>.
   Each row is an inner HakiArray* of char* fields.              */
void* csv__parse(const char* data) {
    void* outer = haki_array_new(sizeof(void*));
    if (!data) return outer;
    /* Split data into lines */
    const char* p = data;
    while (1) {
        /* Find end of line */
        const char* nl = strchr(p, '\n');
        size_t row_len = nl ? (size_t)(nl - p) : strlen(p);
        /* Parse fields in this row */
        void* inner = haki_array_new(sizeof(void*));
        const char* fp = p;
        const char* row_end = p + row_len;
        while (fp <= row_end) {
            const char* comma = (const char*)memchr(fp, ',', (size_t)(row_end - fp));
            size_t flen = comma ? (size_t)(comma - fp) : (size_t)(row_end - fp);
            char* field = (char*)malloc(flen + 1);
            memcpy(field, fp, flen);
            field[flen] = '\0';
            haki_array_append(inner, &field);
            if (!comma) break;
            fp = comma + 1;
        }
        haki_array_append(outer, &inner);
        if (!nl) break;
        p = nl + 1;
    }
    return outer;
}

/* ── Crypto module ───────────────────────────────────────────────────────────── */

/* SHA-256 implementation */
static const uint32_t SHA256_K[64] = {
    0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
    0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
    0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
    0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
    0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
    0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
};
#define SHA256_ROTR(x,n) (((x)>>(n))|((x)<<(32-(n))))
#define SHA256_SHR(x,n)  ((x)>>(n))
#define SHA256_CH(x,y,z) (((x)&(y))^(~(x)&(z)))
#define SHA256_MAJ(x,y,z)(((x)&(y))^((x)&(z))^((y)&(z)))
#define SHA256_EP0(x) (SHA256_ROTR(x,2)^SHA256_ROTR(x,13)^SHA256_ROTR(x,22))
#define SHA256_EP1(x) (SHA256_ROTR(x,6)^SHA256_ROTR(x,11)^SHA256_ROTR(x,25))
#define SHA256_SIG0(x)(SHA256_ROTR(x,7)^SHA256_ROTR(x,18)^SHA256_SHR(x,3))
#define SHA256_SIG1(x)(SHA256_ROTR(x,17)^SHA256_ROTR(x,19)^SHA256_SHR(x,10))

static void sha256_transform(uint32_t state[8], const uint8_t data[64]) {
    uint32_t a,b,c,d,e,f,g,h,t1,t2,w[64];
    int i;
    for (i = 0; i < 16; i++) {
        w[i] = ((uint32_t)data[i*4]<<24)|((uint32_t)data[i*4+1]<<16)|
               ((uint32_t)data[i*4+2]<<8)|(uint32_t)data[i*4+3];
    }
    for (; i < 64; i++)
        w[i] = SHA256_SIG1(w[i-2]) + w[i-7] + SHA256_SIG0(w[i-15]) + w[i-16];
    a=state[0]; b=state[1]; c=state[2]; d=state[3];
    e=state[4]; f=state[5]; g=state[6]; h=state[7];
    for (i = 0; i < 64; i++) {
        t1 = h + SHA256_EP1(e) + SHA256_CH(e,f,g) + SHA256_K[i] + w[i];
        t2 = SHA256_EP0(a) + SHA256_MAJ(a,b,c);
        h=g; g=f; f=e; e=d+t1; d=c; c=b; b=a; a=t1+t2;
    }
    state[0]+=a; state[1]+=b; state[2]+=c; state[3]+=d;
    state[4]+=e; state[5]+=f; state[6]+=g; state[7]+=h;
}

static void sha256_hash(const uint8_t* data, size_t len, uint8_t digest[32]) {
    uint32_t state[8] = {
        0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,
        0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19
    };
    uint8_t block[64];
    size_t i;
    uint64_t bitlen = (uint64_t)len * 8;
    /* Process full blocks */
    size_t full = len / 64;
    for (i = 0; i < full; i++) sha256_transform(state, data + i*64);
    /* Pad */
    size_t rem = len % 64;
    memcpy(block, data + full*64, rem);
    block[rem++] = 0x80;
    if (rem > 56) {
        memset(block + rem, 0, (size_t)(64 - rem));
        sha256_transform(state, block);
        rem = 0;
    }
    memset(block + rem, 0, (size_t)(56 - rem));
    for (i = 0; i < 8; i++) block[56+i] = (uint8_t)(bitlen >> (56 - i*8));
    sha256_transform(state, block);
    for (i = 0; i < 8; i++) {
        digest[i*4]   = (uint8_t)(state[i]>>24);
        digest[i*4+1] = (uint8_t)(state[i]>>16);
        digest[i*4+2] = (uint8_t)(state[i]>>8);
        digest[i*4+3] = (uint8_t)(state[i]);
    }
}

char* crypto__sha256(const char* s) {
    if (!s) s = "";
    uint8_t digest[32];
    sha256_hash((const uint8_t*)s, strlen(s), digest);
    char* hex = (char*)malloc(65);
    for (int i = 0; i < 32; i++) snprintf(hex + i*2, 3, "%02x", digest[i]);
    hex[64] = '\0';
    return hex;
}

static const char B64_TABLE[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

char* crypto__base64Encode(const char* input) {
    if (!input) return strdup("");
    size_t in_len = strlen(input);
    size_t out_len = 4 * ((in_len + 2) / 3) + 1;
    char* out = (char*)malloc(out_len);
    size_t i = 0, o = 0;
    const uint8_t* src = (const uint8_t*)input;
    while (i < in_len) {
        uint32_t octet_a = i < in_len ? src[i++] : 0;
        uint32_t octet_b = i < in_len ? src[i++] : 0;
        uint32_t octet_c = i < in_len ? src[i++] : 0;
        uint32_t triple  = (octet_a << 16) | (octet_b << 8) | octet_c;
        out[o++] = B64_TABLE[(triple >> 18) & 0x3F];
        out[o++] = B64_TABLE[(triple >> 12) & 0x3F];
        out[o++] = B64_TABLE[(triple >>  6) & 0x3F];
        out[o++] = B64_TABLE[(triple >>  0) & 0x3F];
    }
    /* Add padding */
    size_t pad = in_len % 3;
    if (pad > 0) { out[o-1] = '='; if (pad == 1) out[o-2] = '='; }
    out[o] = '\0';
    return out;
}

char* crypto__base64Decode(const char* input) {
    if (!input) return strdup("");
    static const int8_t DEC[256] = {
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,
        52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,
        -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,
        15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,
        -1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,
        41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
        -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
    };
    size_t in_len = strlen(input);
    if (in_len % 4 != 0) return strdup("");
    size_t out_len = in_len / 4 * 3;
    if (in_len > 0 && input[in_len-1] == '=') out_len--;
    if (in_len > 1 && input[in_len-2] == '=') out_len--;
    char* out = (char*)malloc(out_len + 1);
    size_t i = 0, o = 0;
    while (i < in_len) {
        uint32_t sextet_a = input[i]   == '=' ? 0 & i++ : (uint32_t)DEC[(uint8_t)input[i++]];
        uint32_t sextet_b = input[i]   == '=' ? 0 & i++ : (uint32_t)DEC[(uint8_t)input[i++]];
        uint32_t sextet_c = input[i]   == '=' ? 0 & i++ : (uint32_t)DEC[(uint8_t)input[i++]];
        uint32_t sextet_d = input[i]   == '=' ? 0 & i++ : (uint32_t)DEC[(uint8_t)input[i++]];
        uint32_t triple = (sextet_a << 18) | (sextet_b << 12) | (sextet_c << 6) | sextet_d;
        if (o < out_len) out[o++] = (char)(triple >> 16);
        if (o < out_len) out[o++] = (char)(triple >>  8);
        if (o < out_len) out[o++] = (char)(triple >>  0);
    }
    out[o] = '\0';
    return out;
}

/* ── JSON module ─────────────────────────────────────────────────────────────── */

/* Global JSON value type registry — maps pointer → type tag.
   'S'=string, 'I'=integer, 'B'=bool, 'O'=object(HakiMap*), 'A'=array(HakiArray*)  */
#define HAKI_JSON_REG_CAP 8192
typedef struct { uintptr_t ptr; uint8_t tag; } HakiJsonReg;
static HakiJsonReg _json_reg[HAKI_JSON_REG_CAP];
static int64_t _json_reg_len = 0;

static void json_reg_set(void* p, uint8_t tag) {
    uintptr_t up = (uintptr_t)p;
    for (int64_t i = 0; i < _json_reg_len; i++) {
        if (_json_reg[i].ptr == up) { _json_reg[i].tag = tag; return; }
    }
    if (_json_reg_len < HAKI_JSON_REG_CAP) {
        _json_reg[_json_reg_len].ptr = up;
        _json_reg[_json_reg_len].tag = tag;
        _json_reg_len++;
    }
}
static uint8_t json_reg_get(void* p) {
    uintptr_t up = (uintptr_t)p;
    for (int64_t i = 0; i < _json_reg_len; i++) {
        if (_json_reg[i].ptr == up) return _json_reg[i].tag;
    }
    return 0;
}

void* json__object(void) {
    HakiMap* m = haki_map_new(sizeof(void*));
    json_reg_set((void*)m, 'O');
    return (void*)m;
}
void* json__array(void) {
    HakiArray* a = haki_array_new(sizeof(void*));
    json_reg_set((void*)a, 'A');
    return (void*)a;
}
void* json__string(const char* s) {
    /* Return the string pointer itself; register it as a JSON string */
    if (!s) s = "";
    json_reg_set((void*)s, 'S');
    return (void*)s;
}
void* json__number(int64_t n) {
    void* v = (void*)(intptr_t)n;
    json_reg_set(v, 'I');
    return v;
}
void* json__bool(int64_t b) {
    void* v = (void*)(intptr_t)(b ? 1LL : 0LL);
    json_reg_set(v, 'B');
    return v;
}
void* json__null(void) { return NULL; }

/* Forward declaration */
static char* json_encode_val(void* val);

static char* json_encode_object(HakiMap* m) {
    if (!m) return strdup("{}");
    /* Use ordered keys so output is deterministic */
    size_t buf_cap = 256;
    char* buf = (char*)malloc(buf_cap);
    size_t pos = 0;
    buf[pos++] = '{';
    for (int64_t i = 0; i < m->order_len; i++) {
        const char* key = m->order[i];
        void* val = haki_map_get(m, key);
        if (i > 0) buf[pos++] = ',';
        /* Write "key": */
        size_t klen = strlen(key);
        while (pos + klen + 4 >= buf_cap) { buf_cap *= 2; buf = (char*)realloc(buf, buf_cap); }
        buf[pos++] = '"';
        memcpy(buf + pos, key, klen); pos += klen;
        buf[pos++] = '"'; buf[pos++] = ':';
        /* Write value */
        char* enc = json_encode_val(val);
        size_t elen = strlen(enc);
        while (pos + elen + 2 >= buf_cap) { buf_cap *= 2; buf = (char*)realloc(buf, buf_cap); }
        memcpy(buf + pos, enc, elen); pos += elen;
        free(enc);
    }
    while (pos + 2 >= buf_cap) { buf_cap *= 2; buf = (char*)realloc(buf, buf_cap); }
    buf[pos++] = '}'; buf[pos] = '\0';
    return buf;
}

static char* json_encode_array(HakiArray* a) {
    if (!a) return strdup("[]");
    size_t buf_cap = 64;
    char* buf = (char*)malloc(buf_cap);
    size_t pos = 0;
    buf[pos++] = '[';
    for (int64_t i = 0; i < a->length; i++) {
        void* val = *(void**)((char*)a->data + i * a->elem_size);
        if (i > 0) buf[pos++] = ',';
        char* enc = json_encode_val(val);
        size_t elen = strlen(enc);
        while (pos + elen + 2 >= buf_cap) { buf_cap *= 2; buf = (char*)realloc(buf, buf_cap); }
        memcpy(buf + pos, enc, elen); pos += elen;
        free(enc);
    }
    while (pos + 2 >= buf_cap) { buf_cap *= 2; buf = (char*)realloc(buf, buf_cap); }
    buf[pos++] = ']'; buf[pos] = '\0';
    return buf;
}

static char* json_encode_val(void* val) {
    if (!val) return strdup("null");
    uint8_t tag = json_reg_get(val);
    if (tag == 'S') {
        const char* s = (const char*)val;
        size_t len = strlen(s);
        char* r = (char*)malloc(len + 3);
        r[0] = '"'; memcpy(r+1, s, len); r[len+1] = '"'; r[len+2] = '\0';
        return r;
    }
    if (tag == 'I') {
        int64_t n = (int64_t)(intptr_t)val;
        char buf[32]; snprintf(buf, sizeof(buf), "%lld", (long long)n);
        return strdup(buf);
    }
    if (tag == 'B') {
        return strdup((intptr_t)val ? "true" : "false");
    }
    if (tag == 'O') return json_encode_object((HakiMap*)val);
    if (tag == 'A') return json_encode_array((HakiArray*)val);
    /* Unknown — try as null */
    return strdup("null");
}

char* json__encode(void* val) { return json_encode_val(val); }

/* Simple JSON parser */
static const char* json_skip_ws(const char* p) {
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    return p;
}

static void* json_parse_value(const char* p, const char** end);

static void* json_parse_string(const char* p, const char** end) {
    /* p points past the opening '"' */
    char buf[4096]; int pos = 0;
    while (*p && *p != '"') {
        if (*p == '\\') { p++;
            if (*p == '"') buf[pos++] = '"';
            else if (*p == '\\') buf[pos++] = '\\';
            else if (*p == 'n') buf[pos++] = '\n';
            else if (*p == 'r') buf[pos++] = '\r';
            else if (*p == 't') buf[pos++] = '\t';
            else buf[pos++] = *p;
        } else buf[pos++] = *p;
        p++;
    }
    buf[pos] = '\0';
    if (*p == '"') p++;
    *end = p;
    char* s = strdup(buf);
    json_reg_set((void*)s, 'S');
    return (void*)s;
}

static void* json_parse_object(const char* p, const char** end) {
    /* p points past '{' */
    HakiMap* m = haki_map_new(sizeof(void*));
    json_reg_set((void*)m, 'O');
    p = json_skip_ws(p);
    while (*p && *p != '}') {
        p = json_skip_ws(p);
        if (*p != '"') break;
        p++;
        const char* ke; void* key_v = json_parse_string(p, &ke); p = ke;
        const char* key = (const char*)key_v;
        p = json_skip_ws(p);
        if (*p == ':') p++;
        p = json_skip_ws(p);
        const char* ve; void* val = json_parse_value(p, &ve); p = ve;
        haki_map_set(m, key, (void*)(intptr_t)val);
        p = json_skip_ws(p);
        if (*p == ',') p++;
    }
    if (*p == '}') p++;
    *end = p;
    return (void*)m;
}

static void* json_parse_array(const char* p, const char** end) {
    /* p points past '[' */
    HakiArray* a = haki_array_new(sizeof(void*));
    json_reg_set((void*)a, 'A');
    p = json_skip_ws(p);
    while (*p && *p != ']') {
        const char* ve; void* val = json_parse_value(p, &ve); p = ve;
        haki_array_append(a, &val);
        p = json_skip_ws(p);
        if (*p == ',') p++;
        p = json_skip_ws(p);
    }
    if (*p == ']') p++;
    *end = p;
    return (void*)a;
}

static void* json_parse_value(const char* p, const char** end) {
    p = json_skip_ws(p);
    if (!*p) { *end = p; return NULL; }
    if (*p == '"') {
        p++;
        return json_parse_string(p, end);
    }
    if (*p == '{') {
        p++;
        return json_parse_object(p, end);
    }
    if (*p == '[') {
        p++;
        return json_parse_array(p, end);
    }
    if (*p == 't') { /* true */
        void* v = (void*)(intptr_t)1LL;
        json_reg_set(v, 'B');
        *end = p + 4;
        return v;
    }
    if (*p == 'f') { /* false */
        void* v = (void*)(intptr_t)0LL;
        json_reg_set(v, 'B');
        *end = p + 5;
        return v;
    }
    if (*p == 'n') { *end = p + 4; return NULL; } /* null */
    /* Number */
    int64_t n = 0; int neg = 0;
    if (*p == '-') { neg = 1; p++; }
    const char* start = p;
    while (*p >= '0' && *p <= '9') { n = n * 10 + (*p - '0'); p++; }
    if (p == start) { *end = p; return NULL; } /* invalid */
    if (neg) n = -n;
    *end = p;
    void* v = (void*)(intptr_t)n;
    json_reg_set(v, 'I');
    return v;
}

void* json__decode(const char* json_str) {
    if (!json_str) return NULL;
    const char* end;
    return json_parse_value(json_str, &end);
}

const char* haki_json_as_string(void* val) {
    if (!val) return "";
    uint8_t tag = json_reg_get(val);
    if (tag == 'S') return (const char*)val;
    if (tag == 'I') {
        char* buf = (char*)malloc(32);
        snprintf(buf, 32, "%lld", (long long)(int64_t)(intptr_t)val);
        return buf;
    }
    if (tag == 'B') return (intptr_t)val ? "true" : "false";
    return "";
}

/* ── Template module ─────────────────────────────────────────────────────────── */

const char* template__parse(const char* tmpl) {
    /* Template is just the template string itself */
    return tmpl ? tmpl : "";
}

void* template__context(void) {
    /* Context is a HakiMap* (string → string values) */
    HakiMap* m = haki_map_new(sizeof(void*));
    return (void*)m;
}

char* template__render(const char* tmpl, void* ctx) {
    HakiMap* m = (HakiMap*)ctx;
    if (!tmpl) return strdup("");
    size_t buf_cap = strlen(tmpl) * 2 + 256;
    char* buf = (char*)malloc(buf_cap);
    size_t pos = 0;
    const char* p = tmpl;
    while (*p) {
        if (p[0] == '{' && p[1] == '{') {
            const char* start = p + 2;
            const char* close = strstr(start, "}}");
            if (close) {
                size_t klen = (size_t)(close - start);
                char* key = (char*)malloc(klen + 1);
                memcpy(key, start, klen); key[klen] = '\0';
                void* raw = haki_map_get(m, key);
                free(key);
                /* Value stored as (void*)(intptr_t)(char*) — retrieve as char* */
                const char* val = raw ? (const char*)raw : "";
                size_t vlen = strlen(val);
                while (pos + vlen + 2 >= buf_cap) { buf_cap *= 2; buf = (char*)realloc(buf, buf_cap); }
                memcpy(buf + pos, val, vlen); pos += vlen;
                p = close + 2;
                continue;
            }
        }
        if (pos + 2 >= buf_cap) { buf_cap *= 2; buf = (char*)realloc(buf, buf_cap); }
        buf[pos++] = *p++;
    }
    buf[pos] = '\0';
    return buf;
}

/* ── Regex module ────────────────────────────────────────────────────────────── */

/* regex__compile: returns the pattern string as the "compiled" regex handle */
const char* regex__compile(const char* pattern) {
    return pattern ? pattern : "";
}

/* haki_regex_match_first: returns first match string, or NULL if no match */
void* haki_regex_match_first(const char* text, const char* pattern) {
    if (!text || !pattern) return NULL;
    regex_t re;
    if (regcomp(&re, pattern, REG_EXTENDED) != 0) return NULL;
    regmatch_t m;
    void* result = NULL;
    if (regexec(&re, text, 1, &m, 0) == 0) {
        int len = m.rm_eo - m.rm_so;
        char* found = (char*)malloc(len + 1);
        memcpy(found, text + m.rm_so, len);
        found[len] = '\0';
        result = (void*)found;
    }
    regfree(&re);
    return result;
}

/* haki_regex_match_all: returns HakiArray* of all match strings */
void* haki_regex_match_all(const char* text, const char* pattern) {
    HakiArray* arr = haki_array_new(sizeof(void*));
    if (!text || !pattern) return (void*)arr;
    regex_t re;
    if (regcomp(&re, pattern, REG_EXTENDED) != 0) return (void*)arr;
    const char* p = text;
    regmatch_t m;
    while (*p && regexec(&re, p, 1, &m, 0) == 0) {
        int len = m.rm_eo - m.rm_so;
        char* found = (char*)malloc(len + 1);
        memcpy(found, p + m.rm_so, len);
        found[len] = '\0';
        haki_array_append(arr, &found);
        if (m.rm_eo == 0) { p++; } else { p += m.rm_eo; }
    }
    regfree(&re);
    return (void*)arr;
}

/* ── HTTP module ─────────────────────────────────────────────────────────── */
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <errno.h>

typedef struct HakiHttpRoute {
    char method[8];
    char* path;
    void* handler;  /* function pointer placeholder */
} HakiHttpRoute;

typedef struct HakiHttpServer {
    int port;
    int listen_fd;
    int running;
    HakiArray* routes; /* HakiHttpRoute* */
} HakiHttpServer;

typedef struct HakiHttpResponse {
    char* body;
    int64_t status;
} HakiHttpResponse;

typedef struct HakiHttpReq {
    char* body;
    char* method;
    char* path;
} HakiHttpReq;

typedef struct HakiHttpRes {
    int client_fd;
    int sent;
    char* resp_body;
    char* content_type;
    int status_code;
} HakiHttpRes;

void* http__Server(int64_t port) {
    HakiHttpServer* s = (HakiHttpServer*)calloc(1, sizeof(HakiHttpServer));
    s->port = (int)port;
    s->routes = haki_array_new(sizeof(void*));
    s->listen_fd = -1;
    return (void*)s;
}

void* http__Client(void) {
    /* client is a simple handle — just return a non-null marker */
    return (void*)(intptr_t)1;
}

/* Parse first line of HTTP request: "METHOD /path HTTP/1.1\r\n" */
static void parse_request_line(const char* buf, char* method, char* path) {
    int i = 0;
    while (buf[i] && buf[i] != ' ' && i < 7) { method[i] = buf[i]; i++; }
    method[i] = '\0';
    while (buf[i] == ' ') i++;
    int j = 0;
    while (buf[i] && buf[i] != ' ' && buf[i] != '\r' && j < 255) { path[j++] = buf[i++]; }
    path[j] = '\0';
}

/* Read body from HTTP request buffer */
static char* extract_body(const char* buf, int len) {
    const char* sep = strstr(buf, "\r\n\r\n");
    if (!sep) return strdup("");
    sep += 4;
    int body_len = len - (int)(sep - buf);
    if (body_len <= 0) return strdup("");
    char* body = (char*)malloc(body_len + 1);
    memcpy(body, sep, body_len);
    body[body_len] = '\0';
    return body;
}

/* Route storage: array of {method, path, fn_ptr, env} entries.
   handler is the raw lifted-function pointer (slot 0 of the Haki closure
   struct {fn_ptr, env}); env is slot 1, forwarded back on every call so
   handlers that actually capture outer variables still work. Handlers
   with no captures ignore env (see `(void)__env;` in lifted fn bodies). */
typedef struct HakiRoute {
    char method[8];
    char path[256];
    void (*handler)(void*, HakiHttpReq*, HakiHttpRes*);
    void* env;
} HakiRoute;

#define MAX_ROUTES 64
static HakiRoute g_routes[MAX_ROUTES];
static int g_nroutes = 0;
static int g_server_fd = -1;
static pthread_t g_server_thread;
static volatile int g_server_running = 0;

static void send_response(int fd, int status, const char* ctype, const char* body) {
    int blen = body ? (int)strlen(body) : 0;
    char header[512];
    snprintf(header, sizeof(header),
        "HTTP/1.1 %d OK\r\nContent-Type: %s\r\nContent-Length: %d\r\nConnection: close\r\n\r\n",
        status, ctype ? ctype : "text/plain", blen);
    send(fd, header, (int)strlen(header), 0);
    if (body && blen > 0) send(fd, body, blen, 0);
}

static void* server_loop(void* arg) {
    int server_fd = *(int*)arg;
    while (g_server_running) {
        fd_set rfds; FD_ZERO(&rfds); FD_SET(server_fd, &rfds);
        struct timeval tv = {0, 50000};
        int r = select(server_fd + 1, &rfds, NULL, NULL, &tv);
        if (r <= 0) continue;
        struct sockaddr_in addr; socklen_t al = sizeof(addr);
        int cfd = accept(server_fd, (struct sockaddr*)&addr, &al);
        if (cfd < 0) continue;
        char buf[8192]; int n = recv(cfd, buf, sizeof(buf)-1, 0);
        if (n <= 0) { close(cfd); continue; }
        buf[n] = '\0';
        char method[8], path[256];
        parse_request_line(buf, method, path);
        char* body = extract_body(buf, n);
        /* Find matching route */
        int matched = 0;
        for (int i = 0; i < g_nroutes; i++) {
            if (strcmp(g_routes[i].method, method) == 0 &&
                strcmp(g_routes[i].path, path) == 0) {
                HakiHttpReq req = {body, method, path};
                HakiHttpRes res = {cfd, 0, NULL, "text/plain", 200};
                g_routes[i].handler(g_routes[i].env, &req, &res);
                if (!res.sent) {
                    send_response(cfd, res.status_code,
                        res.content_type, res.resp_body);
                }
                matched = 1; break;
            }
        }
        if (!matched) send_response(cfd, 404, "text/plain", "not found");
        free(body);
        close(cfd);
    }
    return NULL;
}

/* res.text(body) and res.json(obj) are method calls on HakiHttpRes* */
void haki_http_res_text(HakiHttpRes* res, const char* body) {
    res->resp_body = body ? strdup(body) : strdup("");
    res->content_type = "text/plain";
    res->status_code = 200;
    send_response(res->client_fd, 200, "text/plain", res->resp_body);
    res->sent = 1;
}

void haki_http_res_json(HakiHttpRes* res, void* obj) {
    const char* encoded = json__encode(obj);
    res->resp_body = encoded ? strdup(encoded) : strdup("{}");
    res->content_type = "application/json";
    res->status_code = 200;
    send_response(res->client_fd, 200, "application/json", res->resp_body);
    res->sent = 1;
}

/* server.get(path, handler) and server.post(path, handler):
   These are method calls — emitter dispatches to haki_http_server_get etc.
   However, handler is a Haki closure/fn — we can't call it directly in C.
   For the test, we use a global route table with direct function pointers.
   The Haki fn value gets stored as an opaque pointer and we call via trampoline. */

/* Haki fn literals compile to closures represented as a malloc'd 2-slot
   array {fn_ptr, env}. `closure` here IS that array (as void*), NOT the
   raw function pointer — extract both slots rather than casting the
   whole array to a function-pointer type (that would call into heap
   data instead of code). */
void haki_http_server_get(HakiHttpServer* s, const char* path, void* closure) {
    if (g_nroutes < MAX_ROUTES) {
        strncpy(g_routes[g_nroutes].method, "GET", 7);
        strncpy(g_routes[g_nroutes].path, path, 255);
        void** cl = (void**)closure;
        g_routes[g_nroutes].handler = (void (*)(void*, HakiHttpReq*, HakiHttpRes*))cl[0];
        g_routes[g_nroutes].env = cl[1];
        g_nroutes++;
    }
}

void haki_http_server_post(HakiHttpServer* s, const char* path, void* closure) {
    if (g_nroutes < MAX_ROUTES) {
        strncpy(g_routes[g_nroutes].method, "POST", 7);
        strncpy(g_routes[g_nroutes].path, path, 255);
        void** cl = (void**)closure;
        g_routes[g_nroutes].handler = (void (*)(void*, HakiHttpReq*, HakiHttpRes*))cl[0];
        g_routes[g_nroutes].env = cl[1];
        g_nroutes++;
    }
}

int64_t haki_http_server_listen_background(HakiHttpServer* s) {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    int opt = 1; setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    struct sockaddr_in addr = {0};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons((uint16_t)s->port);
    bind(fd, (struct sockaddr*)&addr, sizeof(addr));
    listen(fd, 16);
    /* Get actual port */
    socklen_t al = sizeof(addr);
    getsockname(fd, (struct sockaddr*)&addr, &al);
    int actual_port = ntohs(addr.sin_port);
    g_server_fd = fd;
    g_server_running = 1;
    static int sfd_storage;
    sfd_storage = fd;
    pthread_create(&g_server_thread, NULL, server_loop, &sfd_storage);
    /* Small sleep to let thread start */
    struct timespec ts = {0, 50000000}; nanosleep(&ts, NULL);
    return (int64_t)actual_port;
}

void haki_http_server_stop(HakiHttpServer* s) {
    g_server_running = 0;
    pthread_join(g_server_thread, NULL);
    if (g_server_fd >= 0) { close(g_server_fd); g_server_fd = -1; }
    g_nroutes = 0;
}

/* HTTP client: connect, send request, read response */
static HakiHttpResponse* http_request(const char* method, const char* url, const char* body) {
    HakiHttpResponse* resp = (HakiHttpResponse*)calloc(1, sizeof(HakiHttpResponse));
    resp->status = 0;
    resp->body = strdup("");

    /* Parse url: http://host:port/path */
    if (strncmp(url, "http://", 7) != 0) return resp;
    const char* hoststart = url + 7;
    const char* colon = strchr(hoststart, ':');
    const char* slash = strchr(hoststart, '/');
    if (!colon || !slash) return resp;

    char host[128]; int hlen = (int)(colon - hoststart);
    if (hlen >= 128) return resp;
    memcpy(host, hoststart, hlen); host[hlen] = '\0';

    int port = atoi(colon + 1);
    const char* path = slash;

    int fd = socket(AF_INET, SOCK_STREAM, 0);
    struct sockaddr_in addr = {0};
    addr.sin_family = AF_INET;
    addr.sin_port = htons((uint16_t)port);
    inet_pton(AF_INET, host, &addr.sin_addr);
    if (connect(fd, (struct sockaddr*)&addr, sizeof(addr)) != 0) {
        close(fd); return resp;
    }

    int bodylen = body ? (int)strlen(body) : 0;
    char req[4096];
    snprintf(req, sizeof(req),
        "%s %s HTTP/1.1\r\nHost: %s\r\nContent-Length: %d\r\nConnection: close\r\n\r\n%s",
        method, path, host, bodylen, body ? body : "");
    send(fd, req, (int)strlen(req), 0);

    /* Read response */
    char buf[16384]; int total = 0, n;
    struct timeval tv = {5, 0};
    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    while ((n = recv(fd, buf + total, sizeof(buf) - total - 1, 0)) > 0) total += n;
    buf[total] = '\0';
    close(fd);

    /* Parse status */
    if (total > 12) { char sc[4]; memcpy(sc, buf+9, 3); sc[3]='\0'; resp->status = atoi(sc); }
    /* Find body */
    const char* sep = strstr(buf, "\r\n\r\n");
    if (sep) resp->body = strdup(sep + 4);
    return resp;
}

void* haki_http_client_get(void* client, const char* url) {
    return (void*)http_request("GET", url, NULL);
}

void* haki_http_client_post(void* client, const char* url, const char* body) {
    return (void*)http_request("POST", url, body);
}

const char* haki_http_response_body(HakiHttpResponse* r) { return r ? r->body : ""; }
int64_t haki_http_response_status(HakiHttpResponse* r) { return r ? r->status : 0; }

/* Tuple structs for multi-return */
typedef struct { void* f0; void* f1; } __Tuple2;
typedef struct { void* f0; void* f1; void* f2; } __Tuple3;
typedef struct { void* f0; void* f1; void* f2; void* f3; } __Tuple4;

/* Enum typedefs (tagged unions represented as void*) */

/* Forward declarations */
typedef struct MonoProgram mono__MonoProgram;
typedef struct MonoFn mono__MonoFn;
typedef struct EnumDef mono__EnumDef;
typedef struct FnDef compiler__FnDef;
typedef struct StructDef compiler__StructDef;
typedef struct Param compiler__Param;
typedef struct MatchArm compiler__MatchArm;
typedef struct Token compiler__Token;
typedef struct SymTable typeck__SymTable;
typedef struct FnInfo typeck__FnInfo;
typedef struct Scope tinfer__Scope;
typedef struct TypedExpr tinfer__TypedExpr;

/* Function prototypes */

/* Struct definitions */

/* Functions */
