[package]
name    = "haki_codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
haki_ast    = { workspace = true }
haki_mono   = { workspace = true }
haki_typeck = { workspace = true }
thiserror   = { workspace = true }
inkwell     = { version = "0.4", features = ["llvm17-0"] }
llvm-sys    = { version = "170", features = ["prefer-dynamic"] }

[dev-dependencies]
haki_parser = { workspace = true }
haki_stdlib = { workspace = true }
