[package]
name    = "haki_wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
haki_ast    = { workspace = true }
haki_mono   = { workspace = true }
haki_typeck = { workspace = true }
thiserror   = { workspace = true }
wasm-encoder = "0.200"
