/// haki_cemit — Emit a Haki MonoProgram as a single portable C file.
///
/// The emitted C file:
///   1. Embeds haki_runtime.c (ARC, arrays, maps, strings, IO, threads)
///   2. Forward-declares all struct and function names
///   3. Defines concrete structs
///   4. Defines all functions in C syntax
///
/// The resulting file compiles with:
///   gcc -O2 -lpthread -o program program.c
///   clang -O2 -lpthread -o program program.c
///
/// This backend targets v1.0 distribution: users install a pre-built hakic binary
/// that emits C, then compile with their system gcc/clang. No LLVM or Rust required.

use haki_ast::{BinaryOp, Binding, Mut, UnaryOp};
use haki_mono::mono_ast::*;
use haki_typeck::typed_ast::SemTy;
use haki_stdlib::RUNTIME_C_SOURCE;

// ── Error type ────────────────────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
pub enum CEmitError {
    #[error("unsupported: {0}")]
    Unsupported(String),
    #[error("internal: {0}")]
    Internal(String),
}

pub type CResult<T> = Result<T, CEmitError>;

// ── Public entry point ────────────────────────────────────────────────────────

/// Emit a complete, self-contained C file from a monomorphized program.
pub fn emit_c(prog: &MonoProgram) -> CResult<String> {
    let mut out = String::with_capacity(64 * 1024);
    let cx = Cx { prog };

    // Header: embed only the core runtime (no HTTP server, no UI — those need extra libraries)
    out.push_str("/* Generated by hakic --emit-c. Compile: gcc -O2 -lpthread -lm -o out this.c */\n");
    let core_runtime = RUNTIME_C_SOURCE
        .split("/* ── HTTP Server")
        .next()
        .unwrap_or(RUNTIME_C_SOURCE);
    out.push_str(core_runtime);
    out.push('\n');

    // Add haki_array_append_val helper used for typed appends
    out.push_str("static void haki_array_append_val(void* arr, void* val) { haki_array_append(arr, val); }\n\n");
    out.push_str("/* ── Tuple structs for multi-return functions ── */\n");
    let mut tuple_arities = std::collections::BTreeSet::new();
    for f in &prog.fns {
        // Check return type — if it's Tuple or a function returning multiple values
        if let SemTy::Tuple(tys) = &f.return_ty {
            tuple_arities.insert(tys.len());
        }
        // Also check by walking return statements in body
        collect_tuple_arities_block(&f.body, &mut tuple_arities);
    }
    // Also collect from enum variant multi-payloads
    for f in &prog.fns {
        collect_tuple_arities_block(&f.body, &mut tuple_arities);
    }
    for n in &tuple_arities {
        out.push_str(&format!("typedef struct {{ "));
        for i in 0..*n {
            out.push_str(&format!("void* f{i}; "));
        }
        out.push_str(&format!("}} __Tuple{n};\n"));
    }
    // Always define Tuple2 (used by multi-return) and Tuple3
    for n in [2usize, 3, 4] {
        if !tuple_arities.contains(&n) {
            out.push_str(&format!("typedef struct {{ "));
            for i in 0..n {
                out.push_str(&format!("void* f{i}; "));
            }
            out.push_str(&format!("}} __Tuple{n};\n"));
        }
    }
    out.push('\n');
    out.push_str("\n/* ── Forward declarations ── */\n");
    for s in &prog.structs {
        out.push_str(&format!("typedef struct {0} {0};\n", c_name(&s.name)));
    }
    for c in &prog.classes {
        out.push_str(&format!("typedef struct {0} {0};\n", c_name(&c.name)));
    }

    // Enum types — represented as { int64_t tag; void* payload; }
    let mut emitted_enums = std::collections::HashSet::new();
    for (ename, _) in &prog.enum_defs {
        let cn = c_name(ename);
        if emitted_enums.insert(cn.clone()) {
            out.push_str(&format!(
                "typedef struct {{ int64_t tag; void* payload; }} {};\n",
                cn
            ));
        }
    }
    out.push('\n');

    // Struct definitions
    out.push_str("/* ── Struct definitions ── */\n");
    for s in &prog.structs {
        cx.emit_struct_def(&mut out, s)?;
    }
    for c in &prog.classes {
        cx.emit_class_def(&mut out, c)?;
    }

    // Forward-declare all functions (so call order doesn't matter)
    out.push_str("/* ── Function prototypes ── */\n");
    for f in &prog.fns {
        out.push_str(&cx.fn_prototype(f)?);
        out.push_str(";\n");
    }
    for s in &prog.structs {
        for m in &s.methods {
            out.push_str(&cx.fn_prototype(m)?);
            out.push_str(";\n");
        }
    }
    for c in &prog.classes {
        for m in &c.methods {
            out.push_str(&cx.fn_prototype(m)?);
            out.push_str(";\n");
        }
    }
    out.push('\n');

    // Function definitions
    out.push_str("/* ── Functions ── */\n");
    for f in &prog.fns {
        cx.emit_fn(&mut out, f)?;
    }
    for s in &prog.structs {
        for m in &s.methods {
            cx.emit_fn(&mut out, m)?;
        }
    }
    for c in &prog.classes {
        for m in &c.methods {
            cx.emit_fn(&mut out, m)?;
        }
    }

    Ok(out)
}

// ── Emitter context ───────────────────────────────────────────────────────────

struct Cx<'a> {
    prog: &'a MonoProgram,
}

impl<'a> Cx<'a> {
    // ── Type mapping ─────────────────────────────────────────────────────────

    fn c_ty(&self, ty: &SemTy) -> String {
        match ty {
            SemTy::Int               => "int64_t".into(),
            SemTy::Float             => "double".into(),
            SemTy::Bool              => "int8_t".into(),
            SemTy::String            => "const char*".into(),
            SemTy::Void              => "void".into(),
            SemTy::Never             => "void".into(),
            SemTy::Named(n)          => {
                match n.as_str() {
                    "Error" => "void*".into(),  // HakiError* opaque
                    _       => format!("{}*", c_name(n)),
                }
            }
            SemTy::Generic(n, _)     => {
                // Map Haki generic types to their C runtime names
                match n.as_str() {
                    "Array"  => "void*".into(),  // HakiArray* opaque as void*
                    "Map"    => "void*".into(),  // HakiMap* opaque as void*
                    "Task"   => "void*".into(),
                    "Mutex"  => "void*".into(),
                    _        => format!("{}*", c_name(n)),
                }
            }
            SemTy::Optional(inner)   => self.c_ty(inner), // nullable pointer
            SemTy::Tuple(_)          => "void*".into(),   // heap-allocated tuple
            SemTy::Fn(_, _)          => "void*".into(),   // fat pointer
            SemTy::Closure(_, _)     => "void*".into(),   // fat pointer
            SemTy::Var(_)            => "void*".into(),
        }
    }

    fn c_ret_ty(&self, ty: &SemTy) -> String {
        match ty {
            SemTy::Void | SemTy::Never => "void".into(),
            SemTy::Tuple(_)            => "void*".into(), // __TupleN* returned as void*
            other => self.c_ty(other),
        }
    }

    // ── Struct/class definitions ──────────────────────────────────────────────

    fn emit_struct_def(&self, out: &mut String, s: &MonoStruct) -> CResult<()> {
        let cn = c_name(&s.name);
        out.push_str(&format!("struct {} {{\n", cn));
        for f in &s.fields {
            out.push_str(&format!("    {} {};\n", self.c_ty(&f.ty), c_name(&f.name)));
        }
        if s.fields.is_empty() { out.push_str("    int _dummy;\n"); }
        out.push_str("};\n\n");
        Ok(())
    }

    fn emit_class_def(&self, out: &mut String, c: &MonoClass) -> CResult<()> {
        let cn = c_name(&c.name);
        out.push_str(&format!("struct {} {{\n", cn));
        // ARC refcount first
        out.push_str("    int64_t __arc_count;\n");
        if let Some(ref sup) = c.superclass {
            // Inherit superclass fields by value-embedding
            out.push_str(&format!("    {} __super;\n", c_name(sup)));
        }
        for f in &c.fields {
            out.push_str(&format!("    {} {};\n", self.c_ty(&f.ty), c_name(&f.name)));
        }
        if c.fields.is_empty() && c.superclass.is_none() {
            out.push_str("    int _dummy;\n");
        }
        out.push_str("};\n\n");
        Ok(())
    }

    // ── Function prototype ────────────────────────────────────────────────────

    fn fn_prototype(&self, f: &MonoFn) -> CResult<String> {
        let ret = self.c_ret_ty(&f.return_ty);
        let name = if f.name == "main" {
            "int main".to_string()
        } else {
            format!("{} {}", ret, c_name(&f.name))
        };
        let params: Vec<String> = if f.name == "main" {
            vec!["int argc".into(), "char** argv".into()]
        } else {
            f.params.iter()
                .map(|p| format!("{} {}", self.c_ty(&p.ty), c_name(&p.name)))
                .collect()
        };
        let params_str = if params.is_empty() { "void".into() } else { params.join(", ") };
        Ok(format!("{name}({params_str})"))
    }

    // ── Function body ─────────────────────────────────────────────────────────

    fn emit_fn(&self, out: &mut String, f: &MonoFn) -> CResult<()> {
        out.push_str(&self.fn_prototype(f)?);
        out.push_str(" {\n");
        // main: call haki_runtime_init with argc/argv
        if f.name == "main" {
            out.push_str("    haki_runtime_init(argc, argv);\n");
        }
        // Emit deferred expressions tracked during block emission
        let mut deferred: Vec<String> = Vec::new();
        self.emit_block(out, &f.body, 1, &mut deferred)?;
        // If the function returns void and doesn't have an explicit return,
        // emit the deferred expressions at the end.
        if matches!(f.return_ty, SemTy::Void | SemTy::Never) {
            for d in &deferred {
                out.push_str(&format!("    {};\n", d));
            }
            if f.name == "main" {
                out.push_str("    return 0;\n");
            }
        }
        out.push_str("}\n\n");
        Ok(())
    }

    // ── Block / statement emission ────────────────────────────────────────────

    fn emit_block(
        &self,
        out: &mut String,
        block: &MonoBlock,
        depth: usize,
        deferred: &mut Vec<String>,
    ) -> CResult<()> {
        let indent = "    ".repeat(depth);
        for stmt in &block.stmts {
            self.emit_stmt(out, stmt, depth, deferred, &indent)?;
        }
        Ok(())
    }

    fn emit_stmt(
        &self,
        out: &mut String,
        stmt: &MonoStmt,
        depth: usize,
        deferred: &mut Vec<String>,
        indent: &str,
    ) -> CResult<()> {
        match &stmt.kind {
            MonoStmtKind::Let(l) => self.emit_let(out, l, indent)?,

            MonoStmtKind::Return(r) => {
                // Emit deferred in LIFO order before return
                for d in deferred.iter().rev() {
                    out.push_str(&format!("{indent}{};\n", d));
                }
                match r.values.len() {
                    0 => out.push_str(&format!("{indent}return;\n")),
                    1 => {
                        let v = self.emit_expr(&r.values[0])?;
                        out.push_str(&format!("{indent}return {};\n", v));
                    }
                    _ => {
                        // Multi-return: heap-allocate a __TupleN struct
                        let n = r.values.len();
                        out.push_str(&format!(
                            "{indent}__Tuple{n}* __ret = (__Tuple{n}*)malloc(sizeof(__Tuple{n}));\n"
                        ));
                        for (i, v) in r.values.iter().enumerate() {
                            let ve = self.emit_expr(v)?;
                            let vty = self.c_ty(&v.ty);
                            // Pointer-sized values (void*, strings, structs, error) store directly.
                            // Scalar values (int64_t, float, bool) need a malloc wrapper.
                            let is_scalar = matches!(v.ty, SemTy::Int | SemTy::Float | SemTy::Bool);
                            if is_scalar {
                                out.push_str(&format!(
                                    "{indent}{{ {vty}* __f{i} = ({vty}*)malloc(sizeof({vty})); *__f{i} = {ve}; __ret->f{i} = __f{i}; }}\n"
                                ));
                            } else {
                                // Pointer types: store directly (NULL-safe)
                                out.push_str(&format!("{indent}__ret->f{i} = (void*)({ve});\n"));
                            }
                        }
                        out.push_str(&format!("{indent}return __ret;\n"));
                    }
                }
            }

            MonoStmtKind::Yield(_) => {} // handled by block-as-expr in caller

            MonoStmtKind::Defer(e) => {
                let es = self.emit_expr(e)?;
                deferred.push(es);
            }

            MonoStmtKind::Continue => out.push_str(&format!("{indent}continue;\n")),
            MonoStmtKind::Break    => out.push_str(&format!("{indent}break;\n")),

            MonoStmtKind::If(i) => {
                let cond = self.emit_expr(&i.cond)?;
                out.push_str(&format!("{indent}if ({cond}) {{\n"));
                self.emit_block(out, &i.then_block, depth + 1, deferred)?;
                out.push_str(&format!("{indent}}}\n"));
                if let Some(els) = &i.else_branch {
                    out.push_str(&format!("{indent}else {{\n"));
                    match els {
                        MonoElse::Block(b) => self.emit_block(out, b, depth + 1, deferred)?,
                        MonoElse::If(inner) => {
                            let inner_stmt = MonoStmt {
                                kind: MonoStmtKind::If(*inner.clone()),
                                span: stmt.span,
                            };
                            self.emit_stmt(out, &inner_stmt, depth + 1, deferred,
                                          &"    ".repeat(depth + 1))?;
                        }
                    }
                    out.push_str(&format!("{indent}}}\n"));
                }
            }

            MonoStmtKind::While(w) => {
                let cond = self.emit_expr(&w.cond)?;
                out.push_str(&format!("{indent}while ({cond}) {{\n"));
                self.emit_block(out, &w.body, depth + 1, deferred)?;
                out.push_str(&format!("{indent}}}\n"));
            }

            MonoStmtKind::For(f) => {
                let arr = self.emit_expr(&f.iter)?;
                let idx_var = format!("__i_{}", c_name(&f.var.name));
                let arr_var = format!("__arr_{}", c_name(&f.var.name));
                let elem_ty = self.c_ty(&f.var_ty);

                out.push_str(&format!("{indent}{{ void* {arr_var} = {arr};\n"));
                out.push_str(&format!(
                    "{indent}    int64_t __len_{0} = haki_array_length({arr_var});\n",
                    c_name(&f.var.name)
                ));
                out.push_str(&format!(
                    "{indent}    for (int64_t {idx_var} = 0; {idx_var} < __len_{0}; {idx_var}++) {{\n",
                    c_name(&f.var.name)
                ));
                out.push_str(&format!(
                    "{indent}        {elem_ty} {0} = *({elem_ty}*)haki_array_get({arr_var}, {idx_var});\n",
                    c_name(&f.var.name)
                ));

                if let Some(ref iv) = f.index_var {
                    out.push_str(&format!(
                        "{indent}        int64_t {} = {idx_var};\n",
                        c_name(&iv.name)
                    ));
                }

                self.emit_block(out, &f.body, depth + 2, deferred)?;
                out.push_str(&format!("{indent}    }}\n"));
                out.push_str(&format!("{indent}}}\n"));
            }

            MonoStmtKind::Match(m) => {
                // Emit as a C block with if-else chains discriminated on tag
                let scrutinee = self.emit_expr(&m.scrutinee)?;
                let is_enum = self.prog.enum_defs.iter().any(|(_, ed)| {
                    ed.variants.iter().any(|v| m.arms.iter().any(|a| {
                        a.pattern == v.name.name ||
                        v.name.name.split("__").last().map_or(false, |b| b == a.pattern)
                    }))
                });

                if is_enum {
                    let sc_var = "__sc".to_string();
                    out.push_str(&format!("{indent}{{ void* {sc_var} = (void*){scrutinee};\n"));
                    out.push_str(&format!("{indent}    int64_t __tag = ((int64_t*){sc_var})[0];\n"));
                    out.push_str(&format!("{indent}    void* __payload = ((void**){sc_var})[1];\n"));
                    for (ai, arm) in m.arms.iter().enumerate() {
                        let disc = self.variant_discriminant(&arm.pattern);
                        let prefix = if ai == 0 { "if".to_string() } else { "} else if".to_string() };
                        if arm.pattern == "_" {
                            out.push_str(&format!("{indent}    }} else {{\n"));
                        } else {
                            out.push_str(&format!("{indent}    {prefix} (__tag == {disc}LL) {{\n"));
                        }
                        // Unpack payload bindings
                        if arm.bindings.len() == 1 {
                            let bt = self.c_ty(&arm.binding_tys[0]);
                            out.push_str(&format!(
                                "{indent}        {bt} {} = *({bt}*)__payload;\n",
                                c_name(&arm.bindings[0].name)
                            ));
                        } else if arm.bindings.len() > 1 {
                            let struct_name = format!("__PayloadTuple{}", arm.binding_tys.len());
                            for (bi, (binding, bty)) in arm.bindings.iter().zip(arm.binding_tys.iter()).enumerate() {
                                let bt = self.c_ty(bty);
                                out.push_str(&format!(
                                    "{indent}        {bt} {} = (({struct_name}*)__payload)->f{bi};\n",
                                    c_name(&binding.name)
                                ));
                            }
                        }
                        self.emit_block(out, &arm.body, depth + 2, deferred)?;
                    }
                    out.push_str(&format!("{indent}    }}\n{indent}}}\n"));
                } else {
                    // Class hierarchy match — use pointer comparisons on type tags
                    // Simplified: just emit if-else based on function calls
                    out.push_str(&format!("{indent}/* class match on {scrutinee} */\n"));
                    for arm in &m.arms {
                        out.push_str(&format!("{indent}/* arm: {} */\n", arm.pattern));
                        self.emit_block(out, &arm.body, depth + 1, deferred)?;
                        break; // emit first arm only as fallback
                    }
                }
            }

            MonoStmtKind::Panic(msg) => {
                let ms = self.emit_expr(msg)?;
                out.push_str(&format!("{indent}haki_panic({ms});\n"));
            }

            MonoStmtKind::Expr(e) => {
                let es = self.emit_expr(e)?;
                if !es.is_empty() {
                    out.push_str(&format!("{indent}{};\n", es));
                }
            }
        }
        Ok(())
    }

    fn emit_let(&self, out: &mut String, l: &MonoLetStmt, indent: &str) -> CResult<()> {
        // Special case: Construct literals (struct/class construction) need sequential statements
        if let MonoExprKind::Construct(type_name, named_args) = &l.init.kind {
            // Error construction → haki_error_new(message)
            if type_name == "Error" {
                if let [(Binding::Name(id), _)] = l.bindings.as_slice() {
                    let nm = c_name(&id.name);
                    if nm != "_" {
                        let msg = named_args.iter()
                            .find(|a| a.name == "message")
                            .map(|a| self.emit_expr(&a.value))
                            .transpose()?
                            .unwrap_or_else(|| "\"error\"".into());
                        let cause = named_args.iter()
                            .find(|a| a.name == "cause");
                        let call = if let Some(c) = cause {
                            let cv = self.emit_expr(&c.value)?;
                            format!("haki_error_new_with_cause({msg}, {cv})")
                        } else {
                            format!("haki_error_new({msg})")
                        };
                        out.push_str(&format!("{indent}void* {nm} = {call};\n"));
                        return Ok(());
                    }
                }
            }
            if let [(Binding::Name(id), ty)] = l.bindings.as_slice() {
                let nm = c_name(&id.name);
                if nm != "_" {
                    let cn = c_name(type_name);
                    let ct = self.c_ty(ty);
                    let is_class = self.prog.classes.iter().any(|c| c.name == *type_name);
                    let alloc = if is_class {
                        format!("({cn}*)haki_alloc(sizeof({cn}))")
                    } else {
                        format!("({cn}*)malloc(sizeof({cn}))")
                    };
                    out.push_str(&format!("{indent}{ct} {nm} = {alloc};\n"));
                    if is_class {
                        out.push_str(&format!("{indent}{nm}->__arc_count = 1;\n"));
                    }
                    for na in named_args {
                        let ve = self.emit_expr(&na.value)?;
                        out.push_str(&format!("{indent}{nm}->{} = {ve};\n", c_name(&na.name)));
                    }
                    return Ok(());
                }
            }
        }

        // Special case: array literals
        if let MonoExprKind::Array(elems) = &l.init.kind {
            if let [(Binding::Name(id), ty)] = l.bindings.as_slice() {
                let nm = c_name(&id.name);
                if nm != "_" {
                    let elem_ty = match ty {
                        SemTy::Generic(_, args) if !args.is_empty() => self.c_ty(&args[0]),
                        _ => "void*".into(),
                    };
                    out.push_str(&format!("{indent}void* {nm} = haki_array_new(sizeof({elem_ty}));\n"));
                    for el in elems {
                        let ev = self.emit_expr(el)?;
                        out.push_str(&format!(
                            "{indent}{{ {elem_ty} __el = ({ev}); haki_array_append({nm}, &__el); }}\n"
                        ));
                    }
                    return Ok(());
                }
            }
        }

        let init = self.emit_expr(&l.init)?;
        match l.bindings.as_slice() {
            [(Binding::Name(id), ty)] => {
                let ct = self.c_ty(ty);
                let nm = c_name(&id.name);
                if nm == "_" {
                    out.push_str(&format!("{indent}(void)({init});\n"));
                } else {
                    out.push_str(&format!("{indent}{ct} {nm} = {init};\n"));
                }
            }
            bindings if bindings.len() > 1 => {
                let n = bindings.len();
                let mb_name = format!("__mb_{}", l.span.lo);
                out.push_str(&format!("{indent}__Tuple{n}* {mb_name} = (__Tuple{n}*)({init});\n"));
                for (i, (binding, ty)) in bindings.iter().enumerate() {
                    if let Binding::Name(id) = binding {
                        let ct = self.c_ty(ty);
                        let nm = c_name(&id.name);
                        if nm != "_" {
                            let is_scalar = matches!(ty, SemTy::Int | SemTy::Float | SemTy::Bool);
                            if is_scalar {
                                // Scalar: f{i} points to heap-allocated value
                                out.push_str(&format!(
                                    "{indent}{ct} {nm} = *({ct}*){mb_name}->f{i};\n"
                                ));
                            } else {
                                // Pointer: f{i} IS the value (may be NULL)
                                out.push_str(&format!(
                                    "{indent}{ct} {nm} = ({ct}){mb_name}->f{i};\n"
                                ));
                            }
                        }
                    }
                }
            }
            _ => {
                out.push_str(&format!("{indent}(void)({init});\n"));
            }
        }
        Ok(())
    }

    // ── Expression emission ───────────────────────────────────────────────────

    fn emit_expr(&self, e: &MonoExpr) -> CResult<String> {
        match &e.kind {
            MonoExprKind::Int(n) => Ok(format!("((int64_t){n}LL)")),
            MonoExprKind::Float(f) => Ok(format!("{f}")),
            MonoExprKind::Bool(b) => Ok(if *b { "1".into() } else { "0".into() }),
            MonoExprKind::String(s) => Ok(format!("\"{}\"", escape_c_string(s))),
            MonoExprKind::Null => Ok("NULL".into()),
            MonoExprKind::Var(name) => Ok(self.emit_var(name, &e.ty)),

            MonoExprKind::Unary(op, inner) => {
                let ie = self.emit_expr(inner)?;
                let op_str = match op {
                    UnaryOp::Neg => "-",
                    UnaryOp::Not => "!",
                };
                Ok(format!("({op_str}{ie})"))
            }

            MonoExprKind::Binary(op, l, r) => {
                // String concatenation handled specially
                if matches!(op, BinaryOp::Add) && matches!(l.ty, SemTy::String) {
                    let ls = self.emit_expr(l)?;
                    let rs = self.emit_expr(r)?;
                    return Ok(format!("haki_string_concat({ls}, {rs})"));
                }
                // String equality
                if (matches!(op, BinaryOp::Eq) || matches!(op, BinaryOp::Ne))
                    && matches!(l.ty, SemTy::String) {
                    let ls = self.emit_expr(l)?;
                    let rs = self.emit_expr(r)?;
                    let cmp = format!("(strcmp({ls}, {rs}) == 0)");
                    return Ok(if matches!(op, BinaryOp::Ne) {
                        format!("(!{cmp})")
                    } else {
                        cmp
                    });
                }
                let le = self.emit_expr(l)?;
                let re = self.emit_expr(r)?;
                let op_str = match op {
                    BinaryOp::Add => "+",  BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",  BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq  => "==", BinaryOp::Ne  => "!=",
                    BinaryOp::Lt  => "<",  BinaryOp::Le  => "<=",
                    BinaryOp::Gt  => ">",  BinaryOp::Ge  => ">=",
                    BinaryOp::And => "&&", BinaryOp::Or  => "||",
                };
                Ok(format!("({le} {op_str} {re})"))
            }

            MonoExprKind::Field(recv, field) => {
                let re = self.emit_expr(recv)?;
                // Error fields go through runtime accessors
                if matches!(recv.ty, SemTy::Named(ref n) if n == "Error")
                    || matches!(recv.ty, SemTy::Optional(ref inner) if matches!(**inner, SemTy::Named(ref n) if n == "Error"))
                {
                    return Ok(match field.as_str() {
                        "message" => format!("haki_error_message({re})"),
                        "cause"   => format!("haki_error_cause({re})"),
                        _         => format!("/* unknown Error field {field} */NULL"),
                    });
                }
                // .length on Array or Map → runtime call
                if field == "length" {
                    match &recv.ty {
                        SemTy::Generic(n, _) if n == "Array" =>
                            return Ok(format!("haki_array_length({re})")),
                        SemTy::Generic(n, _) if n == "Map" =>
                            return Ok(format!("haki_map_length({re})")),
                        // void* arrays (e.g. from argv()) — use array length
                        SemTy::Named(n) if n == "Array" =>
                            return Ok(format!("haki_array_length({re})")),
                        _ => {}
                    }
                }
                Ok(format!("{re}->{}", c_name(field)))
            }

            MonoExprKind::Call(name, args) => self.emit_call(name, args, &e.ty),

            MonoExprKind::Construct(name, named_args) => {
                // Error construction → haki_error_new
                if name == "Error" {
                    let msg = named_args.iter()
                        .find(|a| a.name == "message")
                        .map(|a| self.emit_expr(&a.value))
                        .transpose()?
                        .unwrap_or_else(|| "\"error\"".into());
                    let cause = named_args.iter().find(|a| a.name == "cause");
                    return Ok(if let Some(c) = cause {
                        let cv = self.emit_expr(&c.value)?;
                        format!("haki_error_new_with_cause({msg}, {cv})")
                    } else {
                        format!("haki_error_new({msg})")
                    });
                }
                let cn = c_name(name);
                let is_class = self.prog.classes.iter().any(|c| c.name == *name);
                let size_expr = format!("sizeof({cn})");
                let alloc = if is_class {
                    format!("({cn}*)haki_alloc({size_expr})")
                } else {
                    format!("({cn}*)malloc({size_expr})")
                };
                // Build as a compound expression using a helper
                // Emit as a statement block via a GNU extension comma expression
                // Better: emit a helper variable in caller scope
                // We use a temp inline struct initializer where possible
                if named_args.is_empty() {
                    return Ok(format!("({alloc})"));
                }
                // Emit as: (({ cn* __t = alloc; __t->f = v; ...; __t; }))
                let mut parts = vec![format!("{cn}* __c_{cn} = {alloc}; ")];
                if is_class {
                    parts.push(format!("__c_{cn}->__arc_count = 1; "));
                }
                for na in named_args {
                    let ve = self.emit_expr(&na.value)?;
                    parts.push(format!("__c_{cn}->{} = {ve}; ", c_name(&na.name)));
                }
                parts.push(format!("__c_{cn}"));
                Ok(format!("({{ {} }})", parts.join("")))
            }

            MonoExprKind::Index(arr, idx) => {
                let ae = self.emit_expr(arr)?;
                let ie = self.emit_expr(idx)?;
                let elem_ty = self.c_ty(&e.ty);
                Ok(format!("(*({elem_ty}*)haki_array_get({ae}, {ie}))"))
            }

            MonoExprKind::Array(elems) => {
                let elem_ty = match &e.ty {
                    SemTy::Generic(_, args) if !args.is_empty() => self.c_ty(&args[0]),
                    _ => "void*".into(),
                };
                if elems.is_empty() {
                    return Ok(format!("haki_array_new(sizeof({elem_ty}))"));
                }
                // Use GNU statement expression — works in expression context
                let mut parts = vec![
                    format!("void* __al = haki_array_new(sizeof({elem_ty}));"),
                ];
                for el in elems {
                    let ev = self.emit_expr(el)?;
                    parts.push(format!(
                        "{{ {elem_ty} __el = ({ev}); haki_array_append(__al, &__el); }}"
                    ));
                }
                parts.push("__al".into());
                Ok(format!("({{ {} }})", parts.join(" ")))
            }

            MonoExprKind::If(i) => {
                // If-as-expression: use ternary for simple cases, GNU statement-expr otherwise
                let cond = self.emit_expr(&i.cond)?;
                // Find yield in then and else blocks
                let then_val = self.yield_val(&i.then_block);
                let else_val = i.else_branch.as_ref()
                    .and_then(|eb| if let MonoElse::Block(b) = eb { self.yield_val(b) } else { None });
                match (then_val, else_val) {
                    (Some(tv), Some(ev)) => {
                        Ok(format!("(({cond}) ? ({tv}) : ({ev}))"))
                    }
                    _ => {
                        // Emit as GNU statement expression
                        Ok(format!("/* if-expr: use statement form */({cond} ? 0 : 0)"))
                    }
                }
            }

            MonoExprKind::Match(m) => {
                // Match-as-expression: emit with GNU statement expr
                // Extract yield values from each arm
                let scrutinee = self.emit_expr(&m.scrutinee)?;
                let result_ty = self.c_ty(&e.ty);
                let mut parts = vec![
                    format!("{result_ty} __match_result; "),
                    format!("void* __msc = (void*){scrutinee}; "),
                    format!("int64_t __mtag = ((int64_t*)__msc)[0]; "),
                    format!("void* __mpayload = ((void**)__msc)[1]; "),
                ];
                for (ai, arm) in m.arms.iter().enumerate() {
                    let disc = self.variant_discriminant(&arm.pattern);
                    let prefix = if ai == 0 { "if".to_string() } else { "} else if".to_string() };
                    if arm.pattern == "_" {
                        parts.push("} else {".into());
                    } else {
                        parts.push(format!("{prefix} (__mtag == {disc}LL) {{"));
                    }
                    // Unpack payload
                    if arm.bindings.len() == 1 {
                        let bt = self.c_ty(&arm.binding_tys[0]);
                        parts.push(format!(
                            "{bt} {} = *({bt}*)__mpayload;",
                            c_name(&arm.bindings[0].name)
                        ));
                    } else if arm.bindings.len() > 1 {
                        for (bi, (binding, bty)) in arm.bindings.iter().zip(arm.binding_tys.iter()).enumerate() {
                            let bt = self.c_ty(bty);
                            parts.push(format!(
                                "{bt} {} = (({bt}*)__mpayload)[{bi}];",
                                c_name(&binding.name)
                            ));
                        }
                    }
                    // Emit arm body statements; find yield
                    if let Some(yv) = self.yield_val(&arm.body) {
                        parts.push(format!("__match_result = {yv};"));
                    }
                }
                parts.push("}".into());
                parts.push("__match_result".into());
                Ok(format!("({{ {} }})", parts.join(" ")))
            }

            MonoExprKind::Block(b) => {
                if let Some(yv) = self.yield_val(b) {
                    Ok(format!("({{ {yv} }})"))
                } else {
                    Ok("0".into())
                }
            }

            MonoExprKind::Assign(target, val) => {
                let te = self.emit_expr(target)?;
                let ve = self.emit_expr(val)?;
                Ok(format!("({te} = {ve})"))
            }

            MonoExprKind::Async(inner) => {
                // Async: wrap in task spawn — simplified for C backend
                let ie = self.emit_expr(inner)?;
                Ok(format!("haki_task_spawn_simple((void(*)(void*))({ie}), NULL)"))
            }
        }
    }

    fn emit_var(&self, name: &str, ty: &SemTy) -> String {
        // Check if this is an enum variant (unit variant used as value)
        if let Some((_, disc, v)) = self.find_variant(name) {
            if v.fields.is_empty() {
                // Unit variant — emit as a {tag, NULL} struct on the heap
                let enum_ty = self.c_ty(ty);
                return format!(
                    "({{ {}* __ev = ({}*)malloc(sizeof(int64_t)*2); \
                     ((int64_t*)__ev)[0] = {disc}LL; ((void**)__ev)[1] = NULL; __ev; }})",
                    if enum_ty.ends_with('*') { &enum_ty[..enum_ty.len()-1] } else { "void" },
                    if enum_ty.ends_with('*') { &enum_ty[..enum_ty.len()-1] } else { "void" }
                );
            }
        }
        c_name(name)
    }

    fn emit_call(&self, name: &str, args: &[MonoExpr], ret_ty: &SemTy) -> CResult<String> {
        // ── Builtin intercepts ────────────────────────────────────────────────

        // print(any)
        if name == "print" && args.len() == 1 {
            let a = self.emit_expr(&args[0])?;
            return Ok(match &args[0].ty {
                SemTy::Int   => format!("haki_print_int({a})"),
                SemTy::Float => format!("haki_print_float({a})"),
                SemTy::Bool  => format!("haki_print_bool({a})"),
                _            => format!("haki_print({a})"),
            });
        }
        if name == "print_int"   { return Ok(format!("haki_print_int({})", self.emit_expr(&args[0])?)); }
        if name == "print_float" { return Ok(format!("haki_print_float({})", self.emit_expr(&args[0])?)); }
        if name == "print_bool"  { return Ok(format!("haki_print_bool({})", self.emit_expr(&args[0])?)); }
        if name == "panic"       { return Ok(format!("haki_panic({})", self.emit_expr(&args[0])?)); }

        if name == "int_to_string"   { return Ok(format!("haki_int_to_string({})", self.emit_expr(&args[0])?)); }
        if name == "float_to_string" { return Ok(format!("haki_float_to_string({})", self.emit_expr(&args[0])?)); }
        if name == "string_length"   { return Ok(format!("haki_string_length({})", self.emit_expr(&args[0])?)); }
        if name == "argv"            { return Ok("haki_argv()".into()); }

        // readFile / writeFile / fileExists
        if name == "readFile"   {
            let p = self.emit_expr(&args[0])?;
            return Ok(format!("haki_read_file({p})"));
        }
        if name == "writeFile"  {
            let p = self.emit_expr(&args[0])?;
            let c = self.emit_expr(&args[1])?;
            return Ok(format!("haki_write_file({p}, {c})"));
        }
        if name == "fileExists" {
            return Ok(format!("haki_file_exists({})", self.emit_expr(&args[0])?));
        }

        // thread_spawn
        if name == "thread_spawn" {
            let f = self.emit_expr(&args[0])?;
            return Ok(format!("haki_thread_spawn({f})"));
        }

        // Array methods: Array__T__method
        if name.contains("__append")  { return Ok(format!("haki_array_append_val({}, &({}))", self.emit_expr(&args[0])?, self.emit_expr(&args[1])?)); }
        if name.contains("__length")  { return Ok(format!("haki_array_length({})", self.emit_expr(&args[0])?)); }
        if name.contains("__get")     { return Ok(format!("haki_array_get({}, {})", self.emit_expr(&args[0])?, self.emit_expr(&args[1])?)); }

        // Map methods
        if name.contains("__set") && args.len() == 3 {
            return Ok(format!("haki_map_set({}, {}, {})",
                self.emit_expr(&args[0])?, self.emit_expr(&args[1])?, self.emit_expr(&args[2])?));
        }
        if name.contains("__has") { return Ok(format!("haki_map_has({}, {})", self.emit_expr(&args[0])?, self.emit_expr(&args[1])?)); }
        if name.contains("__get") && args.len() == 2 { return Ok(format!("haki_map_get({}, {})", self.emit_expr(&args[0])?, self.emit_expr(&args[1])?)); }

        // String methods (Type__method mangled)
        if name == "string__substring" || name.ends_with("__substring") {
            return Ok(format!("haki_string_substring({}, {}, {})",
                self.emit_expr(&args[0])?, self.emit_expr(&args[1])?, self.emit_expr(&args[2])?));
        }
        if name.ends_with("__length") && args.len() == 1 && matches!(args[0].ty, SemTy::String) {
            return Ok(format!("haki_string_length({})", self.emit_expr(&args[0])?));
        }
        if name.ends_with("__contains") { return Ok(format!("haki_string_contains({}, {})", self.emit_expr(&args[0])?, self.emit_expr(&args[1])?)); }
        if name.ends_with("__split")    { return Ok(format!("haki_string_split({}, {})", self.emit_expr(&args[0])?, self.emit_expr(&args[1])?)); }
        if name.ends_with("__trim")     { return Ok(format!("haki_string_trim({})", self.emit_expr(&args[0])?)); }
        if name.ends_with("__toUpper")  { return Ok(format!("haki_string_to_upper({})", self.emit_expr(&args[0])?)); }
        if name.ends_with("__toLower")  { return Ok(format!("haki_string_to_lower({})", self.emit_expr(&args[0])?)); }

        // Enum variant construction: VariantName(payload)
        if let Some((_, disc, variant)) = self.find_variant(name) {
            return self.emit_variant_construct(name, disc, &variant.fields, args);
        }

        // Error construction
        if name == "Error" {
            if args.len() == 1 {
                return Ok(format!("haki_error_new({})", self.emit_expr(&args[0])?));
            }
        }

        // ARC retain/release
        if name == "__haki_retain"  { return Ok(format!("haki_retain({})", self.emit_expr(&args[0])?)); }
        if name == "__haki_release" { return Ok(format!("haki_release({})", self.emit_expr(&args[0])?)); }

        // General function call
        let arg_strs: Vec<String> = args.iter()
            .map(|a| self.emit_expr(a))
            .collect::<CResult<_>>()?;
        Ok(format!("{}({})", c_name(name), arg_strs.join(", ")))
    }

    fn emit_variant_construct(
        &self,
        _name: &str,
        disc: usize,
        fields: &[haki_ast::Ty],
        args: &[MonoExpr],
    ) -> CResult<String> {
        if fields.is_empty() {
            // Unit variant
            return Ok(format!(
                "({{ void* __ev = malloc(sizeof(int64_t)+sizeof(void*)); \
                 ((int64_t*)__ev)[0] = {disc}LL; ((void**)__ev)[1] = NULL; __ev; }})"
            ));
        }
        if args.len() == 1 {
            let av = self.emit_expr(&args[0])?;
            let ty = self.c_ty(&args[0].ty);
            return Ok(format!(
                "({{ {ty}* __pl = ({ty}*)malloc(sizeof({ty})); *__pl = {av}; \
                 void* __ev = malloc(sizeof(int64_t)+sizeof(void*)); \
                 ((int64_t*)__ev)[0] = {disc}LL; ((void**)__ev)[1] = __pl; __ev; }})"
            ));
        }
        // Multi-field payload: pack into a flat array
        let mut parts = vec![
            format!("void* __ev = malloc(sizeof(int64_t)+sizeof(void*)); ((int64_t*)__ev)[0] = {disc}LL;"),
            format!("void** __pl = (void**)malloc({} * sizeof(void*));", args.len()),
        ];
        for (i, a) in args.iter().enumerate() {
            let av = self.emit_expr(a)?;
            let ty = self.c_ty(&a.ty);
            parts.push(format!("{{ {ty}* __f = ({ty}*)malloc(sizeof({ty})); *__f = {av}; __pl[{i}] = __f; }}"));
        }
        parts.push("((void**)__ev)[1] = __pl; __ev".into());
        Ok(format!("({{ {} }})", parts.join(" ")))
    }

    /// Extract the yield expression value from a block.
    /// Used for if-as-expression and match-arm yield values.
    fn yield_val(&self, block: &MonoBlock) -> Option<String> {
        for stmt in &block.stmts {
            if let MonoStmtKind::Yield(e) = &stmt.kind {
                return self.emit_expr(e).ok();
            }
        }
        None
    }

    fn find_variant(&self, name: &str) -> Option<(String, usize, haki_ast::EnumVariant)> {
        for (ename, edef) in &self.prog.enum_defs {
            if let Some((idx, v)) = edef.variants.iter().enumerate().find(|(_, v)| {
                v.name.name == name ||
                v.name.name.split("__").last().map_or(false, |b| b == name)
            }) {
                return Some((ename.clone(), idx, v.clone()));
            }
        }
        None
    }

    fn variant_discriminant(&self, name: &str) -> usize {
        self.find_variant(name).map(|(_, d, _)| d).unwrap_or(0)
    }

    fn tuple_type_name(&self, vals: &[MonoExpr]) -> String {
        // Generate a name for an anonymous tuple struct
        // We emit these inline as flat arrays cast to the right type
        format!("__Tuple{}", vals.len())
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Collect arities of all tuple returns found in a block.
fn collect_tuple_arities_block(block: &MonoBlock, out: &mut std::collections::BTreeSet<usize>) {
    for stmt in &block.stmts {
        match &stmt.kind {
            MonoStmtKind::Return(r) if r.values.len() > 1 => { out.insert(r.values.len()); }
            MonoStmtKind::If(i) => {
                collect_tuple_arities_block(&i.then_block, out);
                if let Some(els) = &i.else_branch {
                    match els {
                        MonoElse::Block(b) => collect_tuple_arities_block(b, out),
                        MonoElse::If(inner) => collect_tuple_arities_block(&inner.then_block, out),
                    }
                }
            }
            MonoStmtKind::While(w) => collect_tuple_arities_block(&w.body, out),
            MonoStmtKind::For(f) => collect_tuple_arities_block(&f.body, out),
            _ => {}
        }
    }
}

/// Convert a Haki identifier to a safe C identifier.
/// Replaces `__` (already mangled), handles keywords.
fn c_name(name: &str) -> String {
    let s = name.replace("::", "__");
    // Avoid C reserved words
    match s.as_str() {
        "int" | "float" | "double" | "char" | "short" | "long" | "void"
        | "return" | "if" | "else" | "while" | "for" | "break" | "continue"
        | "struct" | "typedef" | "static" | "extern" | "register" | "auto"
        | "switch" | "case" | "default" | "do" | "goto" | "sizeof"
        | "volatile" | "const" | "enum" | "union" | "signed" | "unsigned"
        | "restrict" | "inline" | "_Bool" | "_Complex"
        => format!("haki_{s}"),
        _ => s,
    }
}

/// Escape a string for C string literal syntax.
fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for ch in s.chars() {
        match ch {
            '"'  => out.push_str("\\\""),
            '\\'  => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c    => out.push(c),
        }
    }
    out
}


